### ISSUE TITLE
Create "Movie" Facet for Movie Format

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#100]
TIU - Will there be a "Movie" facet narrowing to all movie formats? Could that be an option?

**Comment by slknight** [comment]
This is an important limit option.

Movie should include the current format limits

Blu-ray Disc
DVD
Video

I can make a case for also including 16mm film/Film Reel, VideoDisc, and any other legacy formats in Movie as well. Students are not likely to choose legacy formats, but faculty will expect them included in Movie because that is how VF .6 works.

**Comment by gibsonjc** [comment]
CARLI's custom formats from VuFind 0.6 (https://www.carli.illinois.edu/products-services/i-share/opac/vf-formats) (with a few new additions) have now been implemented in VuFind 3 and there is a Movie format.
