### ISSUE TITLE
Need to be able to search for OCLC numbers in 035$a

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#138]
On vufind3-devel, one can't search for an OCLC number in an 035$a with an "All Fields" search (or any search).  

Example in UIUdb BIB 5899902: 
035 __ $a (OCoLC)ocn166391298  
https://vufind3-devel.carli.illinois.edu/vf-uiu/Record/UIUdb.5899902#details 

If you search for any of these three variants of the OCLC number you will get no results:
(OCoLC)ocn166391298
ocn166391298
166391298

Currently in 0.6, searching for ocn166391298 with Keyword will retrieve the record.

I found the definition for the OCLC number at the end of marc.properties:

Extract the numeric portion of the OCLC number using a pattern map:
oclc_num = 035a, (pattern_map.oclc_num)
pattern_map.oclc_num.pattern_0 = [(][Oo][Cc][Oo][Ll][Cc][)][^0-9]*[0]*([0-9]+)=>$1
pattern_map.oclc_num.pattern_1 = ocm[0]*([0-9]+)[ ]*[0-9]*=>$1
pattern_map.oclc_num.pattern_2 = ocn[0]*([0-9]+).*=>$1
pattern_map.oclc_num.pattern_3 = on[0]*([0-9]+).*=>$1

and I notice that our OCLC numbers in 035$a aren't any of these four forms:
(OCoLC)1234567890
ocm12345678
ocn123456789
on1234567890

Ours have both the (OCoLC) and the ocm/ocn/on prefixes on them.  Does this mean we would need to define additional patterns that will account for our forms?
(OCoLC)ocm12345678
(OCoLC)ocn123456789
(OCoLC)on1234567890

**Comment by gibsonjc** [comment]
We need to remember that the MST normalizes 035a OCLC numbers to drop the second prefix (ocm, ocn, on), so the data in the local view and the data in the I-Share view are currently different.

**Comment by cedelis** [comment]
This problem was not related to indexing, as the oclc_num field in Solr was correctly indexed as:

wget -q -O- 'http://localhost:8080/solr/biblio/select?q=id:UIUdb.5899902' 

      <arr name="oclc_num">
        <str>166391298</str>
      </arr>

The problem had to do with the AllFields search in searchspecs.yaml which did not have oclc_num as part of its search spec. I added it to the end, and it now appears to work:

AllFields:
  DismaxFields:
    - title_short^750
    - title_full_unstemmed^600
    - title_full^400
    - title^500
    - title_alt^200
    - title_new^100
    - series^50
    - series2^30
    - author^300
    - author_fuller^150
    - contents^10
    - topic_unstemmed^550
    - topic^500
    - geographic^300
    - genre^300
    - allfields_unstemmed^10
    - fulltext_unstemmed^10
    - allfields
    - fulltext
    - description
    - isbn
    - issn
    - long_lat_display
    - oclc_num



EDIT (Feb 16, 2017): I undid the changes to searchspecs.yaml (adding "- oclc_num"), because it broke our All Fields searches (e.g., search for "cat in the hat" would fail!).

**Comment by cedelis** [comment]
I'm re-opening this issue because even though I have added oclc_num to the AllFields search, it will still not return results if you search "ocm166391298". I thought that the CustomMunge for oclc_num is supposed to strip out non-numerics from the query text which should then result in a search result:

oclc_num:
  CustomMunge:
    oclc_num:
      - [preg_replace, "/[^0-9]/", ""]
      # trim leading zeroes:
      - [preg_replace, "/^0*/", ""]
  QueryFields:
    oclc_num:
      - [oclc_num, ~]



Perhaps I don't understand the yaml spec enough.

**Comment by cedelis** [comment]
I think I know why adding oclc_num to the AllFields edismax query fails. It's because oclc_num is a "string" type whereas all the other AllFields types are "text." This distinction is important because in "text" types, stop words are eliminated (cat in the hat -> cat hat), therefore edismax's different handling of oclc_num field creates havoc in the query as a whole.

I.e.,

edismax's interpretation of AllFields *before* adding oclc_num:

(
    +(
        +DisjunctionMaxQuery(
            (title_new:cat^100.0 | series2:cat^30.0 | author:cat^300.0 | allfields:cat | description:cat | title:cat^500.0 | title_short:cat^750.0 | title_full_unstemmed:cat^600.0 | title_full:cat^400.0 | author_fuller:cat^150.0 | geographic:cat^300.0 | title_alt:cat^200.0 | contents:cat^10.0 | series:cat^50.0 | allfields_unstemmed:cat^10.0 | genre:cat^300.0 | fulltext:cat | topic:cat^500.0 | fulltext_unstemmed:cat^10.0 | topic_unstemmed:cat^550.0 | long_lat_display:cat)
         )
        +DisjunctionMaxQuery(
            (title_new:hat^100.0 | series2:hat^30.0 | author:hat^300.0 | allfields:hat | description:hat | title:hat^500.0 | title_short:hat^750.0 | title_full_unstemmed:hat^600.0 | title_full:hat^400.0 | author_fuller:hat^150.0 | geographic:hat^300.0 | title_alt:hat^200.0 | contents:hat^10.0 | series:hat^50.0 | allfields_unstemmed:hat^10.0 | genre:hat^300.0 | fulltext:hat | topic:hat^500.0 | fulltext_unstemmed:hat^10.0 | topic_unstemmed:hat^550.0 | long_lat_display:hat)
        )
    )
)/no_coord


*after* adding oclc_num (notice how the 'in' 'the' are added to the query in the middle; this causes the query to fail because in order for a record to satisfy it, it would need to have both 'in' and 'the' in the oclc_num, which will most likely never happen!):


(
   +(
      +DisjunctionMaxQuery(
         (title_new:cat^100.0 | oclc_num:cat | series2:cat^30.0 | author:cat^300.0 | allfields:cat | description:cat | title:cat^500.0 | title_short:cat^750.0 | title_full_unstemmed:cat^600.0 | title_full:cat^400.0 | author_fuller:cat^150.0 | geographic:cat^300.0 | title_alt:cat^200.0 | contents:cat^10.0 | series:cat^50.0 | allfields_unstemmed:cat^10.0 | genre:cat^300.0 | fulltext:cat | topic:cat^500.0 | fulltext_unstemmed:cat^10.0 | topic_unstemmed:cat^550.0 | long_lat_display:cat)
      )
      +DisjunctionMaxQuery(
         (oclc_num:in)
      )
      +DisjunctionMaxQuery(
          (oclc_num:the)
      )
      +DisjunctionMaxQuery(
          (title_new:hat^100.0 | oclc_num:hat | series2:hat^30.0 | author:hat^300.0 | allfields:hat | description:hat | title:hat^500.0 | title_short:hat^750.0 | title_full_unstemmed:hat^600.0 | title_full:hat^400.0 | author_fuller:hat^150.0 | geographic:hat^300.0 | title_alt:hat^200.0 | contents:hat^10.0 | series:hat^50.0 | allfields_unstemmed:hat^10.0 | genre:hat^300.0 | fulltext:hat | topic:hat^500.0 | fulltext_unstemmed:hat^10.0 | topic_unstemmed:hat^550.0 | long_lat_display:hat)
      )
   )
)/no_coord


So, what can we do about this? There are 3 approaches that I can think of.

1. switch from edismax to standard query parser. This would require us to build the query like we did in 0.6. I don't really want to go this route, because I'd rather continue following vufind's lead.

2. change the oclc_num type from "string" to "text". This seems the most plausible to me. It would require a complete re-index, of course.

3. Create a separate search type in the catalog, called "OCLC Number Search" (similar to ISSN/ISBN search). This would be the "easiest" solution and could be set up right now (without having to reindex anything).

What are your thoughts?

**Comment by gibsonjc** [comment]
Great sleuthing! 

> So, what can we do about this? There are 3 approaches that I can think of.
> 1. switch from edismax to standard query parser. This would require us to build the query like we did in 0.6. I don't really want to go this route, because I'd rather continue following vufind's lead.
> 2. change the oclc_num type from "string" to "text". This seems the most plausible to me. It would require a complete re-index, of course.
> 3. Create a separate search type in the catalog, called "OCLC Number Search" (similar to ISSN/ISBN search). This would be the "easiest" solution and could be set up right now (without having to reindex anything).

I do not like number 1 either, so let's dismiss it for now.

Tell me more about number 2...

- So by changing it to "text" you think that the OCLC number could then be searched as "All Fields" because everything else in that definition is "text" as well?  
- Any way we can find out why oclc_num was set up as "string" to begin with?  
- What are issn and isbn set as?  I see that I CAN search for ISSNs and ISBNs with "All Fields" successfully:

ISSN Example: 1727-4052
https://vufind3-devel.carli.illinois.edu/all/vf-isu/Search/Results?lookfor=1727-4052&type=AllFields&limit=20&sort=relevance

ISBN Example: 0394900014
https://vufind3-devel.carli.illinois.edu/vf-isu/Search/Results?lookfor=0394900014+&type=AllFields&limit=20&sort=relevance

If "All Fields" isn't really all the fields, that is lying in my book.  But if someone set this one up differently for a reason I'd love to understand why.


Regarding number 3...

This feels the least disruptive out of all three because it doesn't change anything that was already there, it just adds in something that we need in a way that we can understand and use.

UChicago seems to have made a local change where they have an "ISBN, ISSN, etc." search option (instead of "ISBN/ISSN") in their drop down menu that you can use to search the ISBN, ISSN, or OCLC number (maybe more, I can't tell).

Example with OCLC number 14064308: 
https://catalog.lib.uchicago.edu/vufind/Search/Results?lookfor=14064308&type=StandardNumbers&limit=60&sort=relevance

You still can't search for OCLC numbers in their "All Fields" search either, but you can search ISSNs like 0022-314X and ISBNs like 0394900014.  I am not saying their solution is the best, just pointing it out.

**Comment by cedelis** [comment]
You raise very good questions.

'issn' and 'isbn' Solr fields have their own type (isn), so they are different. But in the 'isn' type definition, there doesn't appear to be a solr.StopFilterFactory filter, which is what I had previously thought was the main difference:

   <field name="isbn" type="isn" indexed="true" stored="true" multiValued="true"/>
   <field name="issn" type="isn" indexed="true" stored="true" multiValued="true"/>

    
    <fieldType name="isn" class="solr.TextField" positionIncrementGap="100">
      <analyzer>
        <tokenizer class="solr.PatternTokenizerFactory" pattern="^(\S*)\s*.*$" group="1"/>
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.PatternReplaceFilterFactory" pattern="[^0-9x]" replacement="" replace="all"/>
        <filter class="solr.LengthFilterFactory" min="1" max="100" />
      </analyzer>
    </fieldType>

Something else may be going on here. I'm looking into it...

**Comment by cedelis** [comment]
I'm thinking the choices are now:

1. re-index oclc_num as type 'isn' (assuming we can follow the same pattern; otherwise, create our own type)

2. separate oclc_num into its own search type

**Comment by gibsonjc** [comment]
I don't think I'm qualified to know whether either choice 1 or choice 2 is good or bad or neutral.  I find it extremely odd that OCLC numbers aren't already accommodated by default. And why isn't "All Fields" really searching all of the fields?  Maybe we could ask people on the vufind email list(s) how they have handled searching for OCLC numbers and see if they have come up with other clever options?

**Comment by cedelis** [comment]
I'm not as surprised as you are about OCLC numbers not being included. Other than librarians, who would do this? Option 1 above seems like the best approach to me IMHO. There is a curious thing going on, though, regarding the 'allfields' Solr field. In marc.properties (the parent config file for all of our imports), it is defined using a custom function ("allfields = custom, getAllSearchableFieldsAsSet(100, 900)" which I presume gathers MARC fields between 100 and 900 (inclusive?). However, I do not appear to see the "allfields" field in any of our records. I think I need to see what getAllSearchableFieldsAsSet actually does (it doesn't appear to be an index_java, therefore I'm guessing it is a built-in function coming from SolrIndexer. I might have to peer into SolrMarc internals for this).

**Comment by gibsonjc** [comment]
Interesting.  Maybe that is why in 0.6 our search was renamed to "Keywords" because it only searches 1XX-9XX it doesn't search any of the 00X fields which are numbers/codes.

**Comment by cedelis** [comment]
FYI, Option 2 is by far the easiest, since it doesn't require a re-index. I've temporarily configured UIU local:

https://vufind3-devel.carli.illinois.edu/vf-uiu/Search/Results?lookfor=ocn166391298&type=oclc_num&limit=20&sort=relevance

It seems sort of silly to separate it from ISBN/ISSN, though. But if we wanted to combine OCLC into the ISBN/ISSN like University of Chicago does and call it something like "ISBN, ISSN, etc.", then we would have to change the type of oclc_num from string to isn type and re-index.

**Comment by gibsonjc** [comment]
Discovered that the OCLC number is already indexed in oclc_num, so these three URLs all work to find an the same OCLC number in 035a:

https://vufind3.carli.illinois.edu/vf-eiu/Search/Results?lookfor=(OCoLC)ocm02597226&type=oclc_num

https://vufind3.carli.illinois.edu/vf-eiu/Search/Results?lookfor=ocm02597226&type=oclc_num

https://vufind3.carli.illinois.edu/vf-eiu/Search/Results?lookfor=02597226&type=oclc_num

**Comment by gibsonjc** [comment]
In addition to the URLs using the type=oclc_num in the previous comment, OCLC numbers can also be searched as "All Fields" in any of these forms to find a record:
(OCoLC)ocm02597226
ocm02597226
02597226

So, OCLC numbers can be searched, there just isn't a specific search type for them in the simple or advanced search dropdowns.  If that is desired, a new Issue will be opened.  Closing this Issue.
