### ISSUE TITLE
Remove CSP, HCD, and KEN from Institution "facet"

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#149]
CSPdb
Kendall College
Harringon College of Design

need to be removed from the list of options available in the "Institution" facet under "Narrow Search" in the I-Share view of vufind3-devel

(side note: RESdb is also there)

**Comment by gibsonjc** [comment]
See also Issue #129 "Remove HCD and KEN"

**Comment by gibsonjc** [comment]
This data may not be a stand-alone list.  Maybe it is generated from the available data in the records that are present? If so, we need to focus on removing the records?

**Comment by cedelis** [comment]
In order to remove the facet value, you'd need to remove the records that would return such a facet value, i.e., you'd need to remove the records. In the case of RESdb, where we would actually want to keep the records but remove them from the facet list, then we'd need to write custom code in order to do so; if we simply want to rename RESdb to something else, that's as easy as supplying a translation in languages/en.ini (and since none exists yet for RESdb, you see the value itself: RESdb).

**Comment by gibsonjc** [comment]
Closing.  As of March, we are now stripping 035s that have other databases' prefixes and IDs from records before they enter VuFind 3 and RESdb records that were accidentally in the feed are now removed.
