### ISSUE TITLE
change setting for location of "Most Recent Received Issues" in holdings display

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#150]
In VoyagerRestful.ini in the [Holdings] stanza,:

[Holdings]
; How purchase history is displayed. Supported values are:
; 1) false - Purchase history is not displayed at all.
; 2) true - Purchase history is displayed below other holdings (default)
; 3) "split" - Purchase history is split to each corresponding holdings record and
; displayed by location
purchase_history = true

change to 

purchase_history = split

**Comment by cedelis** [comment]
@gibsonjc I can't seem to find an example that illustrates Purchase History. Can you share an example or two? Thanks!

**Comment by gibsonjc** [comment]
@cedelis 
"Most Recent Received Issues"
https://i-share-test.carli.illinois.edu/vf-isu/Record/ISUdb.494649
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.3920282

**Comment by nmswanson** [comment]
JKM-The way in which serial holdings appear in VuFind 4.1 are rather unhelpful; e.g.: Most Recent Received Issues appear at the bottom, and the list of Volume Holdings is preceded by the copy number. Is listing the volume holdings on a separate 'tab' possible?

RT99919

**Comment by nmswanson** [comment]
LCC- In the old catalog 
<https://vufind.carli.illinois.edu/vf-lcc/Record/lcc_59193>, our newest 
publications were displayed at the top. 
In the new catalog 
<https://i-share.carli.illinois.edu/vf-lcc/Record/LCCdb.59193>, these are 
displayed at the bottom which isn't as useful. 

[This is a good example of what libraries are use to seeing - Most Recent Received Issues (Latest)  at the top.]

RT100068

**Comment by nmswanson** [comment]
ISU- In 0.6 “most recent issues’ are identified by location Floor 2 Current Periodicals [under label “Latest Issues”]
Note: [https://vufind.carli.illinois.edu/vf-isu/Record/isu_177875](https://vufind.carli.illinois.edu/vf-isu/Record/isu_177875)
[In New VuFind: [https://i-share.carli.illinois.edu/vf-isu/Record/ISUdb.177875](https://i-share.carli.illinois.edu/vf-isu/Record/ISUdb.177875)) these are displaying at the bottom of the screen instead of under location: Floor 2 Current Periodicals: Building Use Only]

ISU questions the need to show the “Most Recent Received Issues” data for a title that has been cancelled, especially when it's been a number of years.

email 4/19/18 pg 23

**Comment by nmswanson** [comment]
UIU - reporting on disconnect between latest issues and the holding to which they are linked. Probably this is not an issue in smaller libraries with fewer locations, but for UI, it's a big mess:
https://i-share.carli.illinois.edu/vf-uiu/Record/UIUdb.3899420

The new issues are at ACES, but it looks like they are at Oak because they display at the bottom of the record. 

RT101038

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
That's even better than I expected! Ready for PROD!

**Comment by cedelis** [comment]
In PROD
