### ISSUE TITLE
"Text me" function sometimes sends truncated URLs

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#154]
Some URLs sent in texts were full length and can be used to get back to the record, while other URLs are truncated and will not take you to the record.

Examples:

Texts from GSU that sent full URLs: 
https://vufind3-devel.carli.illinois.edu/vf-gsu/Record/GSUdb.320773 
https://vufind3-devel.carli.illinois.edu/all/vf-gsu/Record/250096272 
https://vufind3-devel.carli.illinois.edu/all/vf-gsu/Record/250233612 
https://vufind3-devel.carli.illinois.edu/all/vf-gsu/Record/250039086 

Texts from GSU that sent truncated URLs: 
https://vufind3-devel.carli.illinois.edu/all/vf-gsu/Record/250132857
https://vufind3-devel.carli.illinois.edu/all/vf-gsu/Record/250039086 
https://vufind3-devel.carli.illinois.edu/all/vf-gsu/Record/263881925 

Transcriptions of truncated texts: 

From: noreply@carli.illinois.edu
Call #:  781.6409048
Location: Lincoln Park Stacks
Are we not new wave?:  https://vufind3-devel.carli.illinois.edu/all

From: noreply@carli.illinois.edu
Call #: ML3534.R6333 2013
Location: Music & Performing Arts
The rock history reader / https://vufind3-devel.carli.illinois.edu/v

**Comment by gibsonjc** [comment]
It seems based on the reports of those that have been retested have been consistently truncated or not truncated.  They don’t change state.  Is that true?

Is there any chance that the truncated URLs were due to some kind of character limit for a text?  Do the ones that are truncated have long titles and/or long locations and/or long call numbers?

**Comment by dmcmpbll** [comment]
Ah! For the ones where the URL is cut off, they all contain 147 characters including spaces (possibly 148 characters depending on if I should have a space between the title and the URL or not- because Iphones divide them into two separate texts I'm uncertain.

For the ones where the full link was sent, they all have less than 147 (or 148) characters. 

See attached word document.

[TextsReceived170303.docx](https://github.com/CARLI/vufind/files/817711/TextsReceived170303.docx)

**Comment by gibsonjc** [comment]
/usr/local/vufind/config/vufind/sms.ini has configurations related to text messaging (like carriers), but nothing about character limits.

**Comment by gibsonjc** [comment]
TRN - When using the “Text this” option, the URL sent in the text appears to be truncated, which makes it nonfunctional. If it’s a character limit issue, it would be more helpful to have as much of the title as will fit instead of the record URL (though keeping the URL--if you can make the whole thing show up in the text--would be nice).

**Comment by cedelis** [comment]
There's not much I can do other than put a cap on some of the fields, which is what I decided to do, for now:

limit TITLE to 30 chars
limit LOCATION to 30 chars

When those two fields reach the limit, I cut out the middle part of the string and replace it with two dots (..)

Commit 1ccfe5f7ec3494f0e9a3cce27dd193107c3fd2af

BTW, this is available on vufind4-devel (not vufind3)

**Comment by dmcmpbll** [comment]
The truncation you did worked well to make the full URL send to my messages!
I also like the shortening of "Location" to "Loc"; that saved some characters too I imagine.

Here is the title I used for testing:
https://vufind3-devel.carli.illinois.edu/vf-prc/Record/PRCdb.795300 
https://vufind4-devel.carli.illinois.edu/vf-prc/Record/PRCdb.795300

See attached PDF for screenshots from my phone.

Is it an option to have the ellipse [...] for longer phrases at the end of the phrase, rather than in the middle?
This example isn't the best for illustrating this, but: 
Location: ebrary eBooks [Online for Pr..
might make more sense to patrons than: 
Loc: ebrary eBooks ..e Patrons Only]

Overall though- the fix seems good!
[VuFindTextMessages.pdf](https://github.com/CARLI/vufind/files/1363863/VuFindTextMessages.pdf)

**Comment by gibsonjc** [comment]
@cedelis Is it an option to have the ellipse [...] for longer phrases at the end of the phrase, rather than in the middle?
This example isn't the best for illustrating this, but:
Location: ebrary eBooks [Online for Pr..
might make more sense to patrons than:
Loc: ebrary eBooks ..e Patrons Only]

**Comment by cedelis** [comment]
Ready for TESTing:

e.g., https://i-share-test.carli.illinois.edu/vf-prc/Record/PRCdb.795300

**Comment by jenhm** [comment]
@gibsonjc asked me to test this and this is what my text on AT&T looked like for the holding above:

Call#:QL737.P98 W95 2008eb
Loc:ebrary eBooks (Online for Pr..
Elephant

It might be nice to have the Title label on there?

**Comment by gibsonjc** [comment]
@jenhm thanks for testing!  Thanks for the suggestion, though I think the Title label will just eat up 7 more characters without a lot of added value, so let's leave as is for now.

@cedelis Go ahead and push to production as is, thanks!

**Comment by cedelis** [comment]
In production
