### ISSUE TITLE
Display of electronic resources links in a consortial environment

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/vufind#16]
JIRA issue created by: Jessica Gibson (gibsonjc)
Originally opened: 2016-03-02 11:06 AM

I'm creating a separate issue for e-resources links display outside of VUFIND2-2 (since that one is for holdings without items not displaying at all).

For the most part, URLs in 856 fields are displaying now, but there are links under and Internet heading and links in the holdings area.  I need to try to figure out where the links are coming from: bib or MFHD.
Example I've been looking at: https://vufind2-test.carli.illinois.edu/all/vf-wiu/Record/194499196

In I-Share, the ability of the user to chose the correct link for their access is critical.

I need to do more testing and set up more examples.

Also none of the 856 subfields that display text about the link are displaying yet: $y $3 $z

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-03-02 11:12 AM

Copying in some commentary from VUFIND2-2:

--------------------
* Why is there a "Recall this?" link anyway, that doesn't make any sense.

Example 1: https://vufind2.carli.illinois.edu/all/vf-uiu/Record/193475824 Leaders in computing changing the digital world
Example 2: https://vufind2.carli.illinois.edu/all/vf-uiu/Record/245666506 One of our thursdays is missing
Example 3: http://vufind2-test.carli.illinois.edu/all/vf-uiu/Record/243196718 Endtimes? crises and turmoil at the New York times, 1999-2009 

-------------------------

E-Resource data should now show up, too. The XCNCIP2 server did contain E-Resource data. I had to add code to VuFind2 to process it:

1. XCNCIP2.php driver now parses out the ns1:HoldingsSet/ns1:ElectronicResource/ns1:ReferenceToResource data, e.g.,

<ns1:ElectronicResource>
<ns1:ReferenceToResource>http://library.aurora.edu/login?url=http://search.ebscohost.com/login.aspx?direct=true&amp;scope=site&amp;db=nlebk&amp;db=nlabk&amp;AN=549562</ns1:ReferenceToResource>
</ns1:ElectronicResource>

... and creates an 'eresource' data field

2. ... which is now read by template themes/bootprint3/templates/RecordTab/holdingsils.phtml which is basically the Detailed Record page.

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-03-24 11:54 AM

I need to make sure URLs don't lie before release.  Do more testing ; use script to evaluate where data comes from; decide about commenting out the "Internet" section

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-04-08 10:46 AM

Internet section is hidden/gone now, but I don't know what made that happen.  Chris, do you remember what you did so we can make a note?

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-04-08 10:58 AM

I've identified three key issues:

Example: https://vufind2-test.carli.illinois.edu/all/vf-wiu/Record/194499196

1. When viewing a record in the "All I-Share Libraries" view, the 856 fields in the bib record are displaying.  Not all of these URL will be appropriate to all users, and a user will have no way to know which one to choose, assuming one is even appropriate.  We should try to find a way to hide all 856 fields from display in "All I-Share Libraries" view.

This example bib has two 856 fields that come from the original TIU bib.  They display to everyone in the I-Share View.  The original CSU bib does not have any 856s in it, so none are represented in the bib.

The MFHD/holdings contain the URL that is appropriate for each institution's users.


2. The URLs that display in the Holdings tab are correct for each library because they are being pulled from the MFHD in each library's db.  However, it is the raw URL in the 856$u only and does not include the other holdings information/text in the $3, $y, and $z.


3. When there is more than one 856 in the MFHD, VuFind2 only appears to be showing the first one.  The TIU MFHD has two 856 fields, and only the first one is displaying

TIU's MFHD 901481 (bib 413487) https://vufind2-test.carli.illinois.edu/vf-tiu/Record/(TIUdb)413487
856 40 ‡3 Full text available: 1995 - . ‡z Available in DOAJ: Directory of Open Access Journals. ‡u http://resolver.ebscohost.com/Redirect/PRL?EPPackageLocationID=642.95235.598445&epcustomerid=s8990416
856 40 ‡3 Full text available: 1995 - . ‡z Available in DOAJ: Directory of Open Access Journals. ‡u http://resolver.ebscohost.com/Redirect/PRL?EPPackageLocationID=642.95235.598445&epcustomerid=s8990416

**Comment by patrickzurek** [comment]
JIRA User: Chris Delis (cedelis)
JIRA Timestamp: 2016-04-08 10:59 AM

commit fa6afbf3cbfc554e8314b2ec38f0b9f53d7f7e96
Author: Chris Delis <cedelis@uillinois.edu>
Date:   Mon Apr 4 11:48:49 2016 -0500

    Comment-out (hide) the E-Resources links from the bib. This causes confusion for aggregated records (All I-Share). Plus, this info should be coming from the MFHD (via XCNCIP holdings), too, which is duplic

M       themes/bootprint3/templates/RecordTab/holdingsils.phtml

**Comment by patrickzurek** [comment]
JIRA User: Chris Delis (cedelis)
JIRA Timestamp: 2016-04-08 11:04 AM

root@vufind2-test:/usr/local/vufind2# git diff ad7ed1f6f9986f2d9bf557ccfe20d589e5e04bd9 themes/bootprint3/templates/RecordTab/holdingsils.phtml
diff --git a/themes/bootprint3/templates/RecordTab/holdingsils.phtml b/themes/bootprint3/templates/RecordTab/holdingsils.phtml
index f01f84f..1adc9c5 100644
--- a/themes/bootprint3/templates/RecordTab/holdingsils.phtml
+++ b/themes/bootprint3/templates/RecordTab/holdingsils.phtml
@@ -39,6 +39,7 @@
 <? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
     <a class="placehold modal-link" title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc('tit
 <? endif; ?>
+
 <? foreach ($holdings as $holding): ?>
 <h3>

**Comment by cedelis** [comment]
B. *The URLs that display in the Holdings tab are correct for each library because they are being pulled from the MFHD in each library's db. However, *it is the raw URL in the 856$u only and does not include the other holdings information/text in the $3, $y, and $z.

*C. When there is more than one 856 in the MFHD, VuFind2 only appears to be showing the first one. *The TIU MFHD has two 856 fields, and only the first one is displaying

Regarding questions B and C above, there is an explanation. The current NCIP definition (based on the version 2.02 schema http://www.niso.org/schemas/ncip/v2_02/ncip_v2_02.xsd ) does not allow for this information. Here's the definition of ElectronicResource:

<xs:element name="ElectronicResource">
    <xs:complexType>
        <xs:sequence>
            <xs:choice>
                <xs:sequence>
                    <xs:element ref="ElectronicDataFormatType"/>
                    <xs:element ref="ActualResource"/>
                </xs:sequence>
                <xs:element ref="ReferenceToResource"/>
            </xs:choice>
            <xs:element ref="Ext" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="ElectronicDataFormatType" type="SchemeValuePair"/>

<xs:complexType name="SchemeValuePair">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="Scheme" type="xs:anyURI"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:element name="ActualResource" type="xs:string"/>

<xs:element name="ReferenceToResource" type="xs:string"/>

This definition only allows for one per HoldingSet (i.e., MFHD), which is why only one is listed (answer to question C). It also does not allow for anything other than a single string to represent the ReferenceToResource (answer to question B). So, currently, there isn't anything we can do about this issue, given today's version of NCIP. I suppose we could make use of some extensions (ns:Ext), but I don't think this is something we'd like to do right now (in beta).

As for question A, I have commented-out all of the bib's open URL links (so that only the holdings' open URLs will display). I did this by commenting out the following template:

[bootprint3]/templates/RecordDriver/SolrDefault/core.phtml:

**Comment by gibsonjc** [comment]
I agree that hiding all bib URLs does take care of issue A where the URLs in a bib may be inappropriate for a user in the I-Share view.  This will be a change from WebVoyage where libraries can decide whether or not to have bib 856 fields display, and VuFind 0.6 where libraries have no choice and bib 856 fields are on for all databases in the local catalog and off in the I-Share union catalog.

Thanks for the explanation and details on NCIP.  I now understand why issue B and C are the way they are given the limitations of the NCIP schema.  In future, I think we should definitely look into other ways to get more data for display.  It seems that NCIP's limitations are a factor in a number of data display problems because its goal is not about display, but about circulating items.

**Comment by gibsonjc** [comment]
A new serious flaw in the display of e-resources links in the I-Share view has been discovered: URLs are being improperly displayed in MFHDs that they don't belong in.

A URL in MFHD 1 shows up there once.
In MFHD 2, MFHD 2's URL and MFHD 1's URL shows up.
In MFHD 3, you see MFHD 3's URL, MFHD 2's URL, and MFHD 1's URL.
etc.

Example 1: (The American journal of photography (OCoLC)875140764 )
https://vufind3.carli.illinois.edu/all/vf-uiu/Record/222647703
UIC's URL appears in their Holding and again in UIU's holding

Example 2: (title: Grand Canyon: tuweep (OCoLC)948299582  )
https://vufind3.carli.illinois.edu/all/vf-sxu/Record/259453728
Each library has the same URL in this example because it is a government publication, but notice how each Holding adds another instance of the URL. 

Example 3: (title: The death and life of American journalism the media revolution that will begin the world again (OCoLC)748371318)
https://vufind3.carli.illinois.edu/all/vf-uiu/Record/256396950
The proxy string for each library is different so you can see how they are repeating in each subsequent Holding.

**Comment by cedelis** [comment]
I solved the "new serious flaw" by noticing (and fixing) a display variable not being initialized properly.

**Comment by gibsonjc** [comment]
These examples in I-Share view with multiple institutions do appear to be fixed now. However, there also appears to be a variant of the duplicating URL when there is more than one MFHD for a *single* institution.
Example: (Tristram Shandy and the editors)
https://vufind3.carli.illinois.edu/vf-eiu/Record/(EIUdb)360183
and
https://vufind3.carli.illinois.edu/all/vf-eiu/Record/249975288
The URL for the electronic version only exists in the Electronic Theses MFHD but appears in the Stacks and Special Collections MFHDs too in both local and I-Share views.

**Comment by gibsonjc** [comment]
Closing this long, mutli-problem Issue in favor of spinning off new standalone Issues for the remaining problems:
#48 
#49 
#50
