### ISSUE TITLE
Copy number displayed is not from MFHD or Item record

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#169]
The copy number being displayed in the Holdings tab is usually not the copy number present in the Voyager MFHD or the Voyager Item Record.  

Additionally, when there are multiple items, VuFind 3 seems to be incrementing the Copy number by one for each item.

Examples:

Incrementing copy numbers:
https://vufind3-devel.carli.illinois.edu/vf-isu/Record/ISUdb.1347336 (but Copy 3 is skipped?!?)
https://vufind3-devel.carli.illinois.edu/vf-mil/Record/MILdb.132645

Says copy 0 but MFHD and Item both say 1:
https://vufind3-devel.carli.illinois.edu/vf-eiu/Record/EIUdb.1146101
https://vufind3-devel.carli.illinois.edu/vf-eiu/Record/EIUdb.783636

But these Say copy 1 and MFHD and Item both say 1:
https://vufind3-devel.carli.illinois.edu/vf-eiu/Record/EIUdb.46278
https://vufind3-devel.carli.illinois.edu/vf-uiu/Record/UIUdb.4637350
https://vufind3-devel.carli.illinois.edu/vf-isu/Record/ISUdb.1842625

**Comment by gibsonjc** [comment]
SIE - Serial holdings are still not showing up correctly.  See holdings  for Facts on file: https://vufind3.carli.illinois.edu/vf-sie/Record/SIEdb.374518
We have 2 holdings records: 1 for the book collection and a suppressed holding record that was for the Ref collection.  I’m not sure why the holdings are showing up twice and what all those copy numbers are.  We only have copy ones.
APSS yearbook holdings show up the same way: 
https://vufind3.carli.illinois.edu/vf-sie/Record/SIEdb.741462
We only have 1 holding record, and all our items are copy 1.

**Comment by gibsonjc** [comment]
TRN - There are multiple holdings appearing on everything that has multiple volumes (e.g. https://vufind3.carli.illinois.edu/vf-trn/Record/TRNdb.1158, https://vufind3.carli.illinois.edu/vf-trn/Record/TRNdb.59121) and the copy numbers are completely messed up (all of the items attached to those records are correctly entered in Voyager as copy 1). It’s a confusing mess. My students will have no idea what to do with that.

**Comment by gibsonjc** [comment]
TIU - Can CARLI edit the way holdings for journal items show? https://vufind3.carli.illinois.edu/vf-tiu/Record/TIUdb.148823 is an example of how journal items show in VuFind 3 (saying we have multiple copies for volumes). [This is critical before TIU can use VuFind 3.]

**Comment by cedelis** [comment]
@gibsonjc , The following is the raw data we currently have to work with for example (the first few records, anyway; not all of them:

https://vufind3-devel.carli.illinois.edu/vf-tiu/Record/TIUdb.148823

The easiest "solution" to this problem is to simply remove the "Copy 0" labels from the display (these numbers are simply enumerated, i.e., they don't come from the holdings data).

******************************HOLDING info
array (
  'id' => '148823',
  'holdings_id' => '163239',
  'item_id' => '400416',
  'status' => 'Not Charged',
  'location' => 'Deerfield Periodical Collection',
  'reserve' => 'N',
  'callnumber' => NULL,
  'barcode' => '3600151289114',
  'use_unknown_message' => false,
  'item_sort_seq' => '0',
  'sort_seq' => 9223372036854775807,
  '_fullRow' =>
  array (
    'BIB_ID' => '148823',
    'MFHD_ID' => '163239',
    'ITEM_BARCODE' => '3600151289114',
    'ITEM_ID' => '400416',
    'ON_RESERVE' => 'N',
    'ITEM_SEQUENCE_NUMBER' => '0',
    'RECALLS_PLACED' => '0',
    'HOLDS_PLACED' => '0',
    'STATUS' => 'Not Charged',
    'RECORD_SEGMENT' => '00324cy  a22001333  450000100070000000400070000700500170001400800330003185200150006486600230007986600260010286600340012886600280016216323914882320120427104135.09807285p    8   4001baeng0000000  bPERIODICAL4080av.1:no.1 (1959)4080av.2-51 (1960-2009)4080xSubscription canceled 20094080xLDR updated 06/23/10',
    'ITEM_ENUM' => 'v.51',
    'LOCATION' => 'Deerfield Periodical Collection',
    'TEMP_LOCATION' => '0',
    'PERM_LOCATION' => '41',
    'CALLNUMBER' => NULL,
    'DUEDATE' => NULL,
    'RETURNDATE' => NULL,
    'SORT_SEQ' => NULL,
    'ITEM_TYPE_ID' => '1',
    'TEMP_ITEM_TYPE_ID' => '0',
    'STATUS_ARRAY' =>
    array (
      0 => 'Not Charged',
    ),
  ),
)
******************************



******************************HOLDING info
array (
  'id' => '148823',
  'holdings_id' => '163239',
  'item_id' => '396820',
  'status' => 'Not Charged',
  'location' => 'Deerfield Periodical Collection',
  'reserve' => 'N',
  'callnumber' => NULL,
  'barcode' => '3600151278098',
  'use_unknown_message' => false,
  'item_sort_seq' => '1',
  'sort_seq' => 9223372036854775807,
  '_fullRow' =>
  array (
    'BIB_ID' => '148823',
    'MFHD_ID' => '163239',
    'ITEM_BARCODE' => '3600151278098',
    'ITEM_ID' => '396820',
    'ON_RESERVE' => 'N',
    'ITEM_SEQUENCE_NUMBER' => '1',
    'RECALLS_PLACED' => '0',
    'HOLDS_PLACED' => '0',
    'STATUS' => 'Not Charged',
    'RECORD_SEGMENT' => '00324cy  a22001333  450000100070000000400070000700500170001400800330003185200150006486600230007986600260010286600340012886600280016216323914882320120427104135.09807285p    8   4001baeng0000000  bPERIODICAL4080av.1:no.1 (1959)4080av.2-51 (1960-2009)4080xSubscription canceled 20094080xLDR updated 06/23/10',
    'ITEM_ENUM' => 'v.50',
    'LOCATION' => 'Deerfield Periodical Collection',
    'TEMP_LOCATION' => '0',
    'PERM_LOCATION' => '41',
    'CALLNUMBER' => NULL,
    'DUEDATE' => NULL,
    'RETURNDATE' => NULL,
    'SORT_SEQ' => NULL,
    'ITEM_TYPE_ID' => '1',
    'TEMP_ITEM_TYPE_ID' => '0',
    'STATUS_ARRAY' =>
    array (
      0 => 'Not Charged',
    ),
  ),
)
******************************



******************************HOLDING info
array (
  'id' => '148823',
  'holdings_id' => '163239',
  'item_id' => '380077',
  'status' => 'Not Charged',
  'location' => 'Deerfield Periodical Collection',
  'reserve' => 'N',
  'callnumber' => NULL,
  'barcode' => '3600151268269',
  'use_unknown_message' => false,
  'item_sort_seq' => '2',
  'sort_seq' => 9223372036854775807,
  '_fullRow' =>
  array (
    'BIB_ID' => '148823',
    'MFHD_ID' => '163239',
    'ITEM_BARCODE' => '3600151268269',
    'ITEM_ID' => '380077',
    'ON_RESERVE' => 'N',
    'ITEM_SEQUENCE_NUMBER' => '2',
    'RECALLS_PLACED' => '0',
    'HOLDS_PLACED' => '0',
    'STATUS' => 'Not Charged',
    'RECORD_SEGMENT' => '00324cy  a22001333  450000100070000000400070000700500170001400800330003185200150006486600230007986600260010286600340012886600280016216323914882320120427104135.09807285p    8   4001baeng0000000  bPERIODICAL4080av.1:no.1 (1959)4080av.2-51 (1960-2009)4080xSubscription canceled 20094080xLDR updated 06/23/10',
    'ITEM_ENUM' => 'v.49',
    'LOCATION' => 'Deerfield Periodical Collection',
    'TEMP_LOCATION' => '0',
    'PERM_LOCATION' => '41',
    'CALLNUMBER' => NULL,
    'DUEDATE' => NULL,
    'RETURNDATE' => NULL,
    'SORT_SEQ' => NULL,
    'ITEM_TYPE_ID' => '1',
    'TEMP_ITEM_TYPE_ID' => '0',
    'STATUS_ARRAY' =>
    array (
      0 => 'Not Charged',
    ),
  ),
)
******************************



******************************HOLDING info
array (
  'id' => '148823',
  'holdings_id' => '163239',
  'item_id' => '370555',
  'status' => 'Not Charged',
  'location' => 'Deerfield Periodical Collection',
  'reserve' => 'N',
  'callnumber' => NULL,
  'barcode' => '3600151261039',
  'use_unknown_message' => false,
  'item_sort_seq' => '3',
  'sort_seq' => 9223372036854775807,
  '_fullRow' =>
  array (
    'BIB_ID' => '148823',
    'MFHD_ID' => '163239',
    'ITEM_BARCODE' => '3600151261039',
    'ITEM_ID' => '370555',
    'ON_RESERVE' => 'N',
    'ITEM_SEQUENCE_NUMBER' => '3',
    'RECALLS_PLACED' => '0',
    'HOLDS_PLACED' => '0',
    'STATUS' => 'Not Charged',
    'RECORD_SEGMENT' => '00324cy  a22001333  450000100070000000400070000700500170001400800330003185200150006486600230007986600260010286600340012886600280016216323914882320120427104135.09807285p    8   4001baeng0000000  bPERIODICAL4080av.1:no.1 (1959)4080av.2-51 (1960-2009)4080xSubscription canceled 20094080xLDR updated 06/23/10',
    'ITEM_ENUM' => 'v.48',
    'LOCATION' => 'Deerfield Periodical Collection',
    'TEMP_LOCATION' => '0',
    'PERM_LOCATION' => '41',
    'CALLNUMBER' => NULL,
    'DUEDATE' => NULL,
    'RETURNDATE' => NULL,
    'SORT_SEQ' => NULL,
    'ITEM_TYPE_ID' => '1',
    'TEMP_ITEM_TYPE_ID' => '0',
    'STATUS_ARRAY' =>
    array (
      0 => 'Not Charged',
    ),
  ),
)
******************************



******************************HOLDING info
array (
  'id' => '148823',
  'holdings_id' => '163239',
  'item_id' => '350792',
  'status' => 'Not Charged',
  'location' => 'Deerfield Periodical Collection',
  'reserve' => 'N',
  'callnumber' => NULL,
  'barcode' => '3600151212457',
  'use_unknown_message' => false,
  'item_sort_seq' => '4',
  'sort_seq' => 9223372036854775807,
  '_fullRow' =>
  array (
    'BIB_ID' => '148823',
    'MFHD_ID' => '163239',
    'ITEM_BARCODE' => '3600151212457',
    'ITEM_ID' => '350792',
    'ON_RESERVE' => 'N',
    'ITEM_SEQUENCE_NUMBER' => '4',
    'RECALLS_PLACED' => '0',
    'HOLDS_PLACED' => '0',
    'STATUS' => 'Not Charged',
    'RECORD_SEGMENT' => '00324cy  a22001333  450000100070000000400070000700500170001400800330003185200150006486600230007986600260010286600340012886600280016216323914882320120427104135.09807285p    8   4001baeng0000000  bPERIODICAL4080av.1:no.1 (1959)4080av.2-51 (1960-2009)4080xSubscription canceled 20094080xLDR updated 06/23/10',
    'ITEM_ENUM' => 'v.47',
    'LOCATION' => 'Deerfield Periodical Collection',
    'TEMP_LOCATION' => '0',
    'PERM_LOCATION' => '41',
    'CALLNUMBER' => NULL,
    'DUEDATE' => NULL,
    'RETURNDATE' => NULL,
    'SORT_SEQ' => NULL,
    'ITEM_TYPE_ID' => '1',
    'TEMP_ITEM_TYPE_ID' => '0',
    'STATUS_ARRAY' =>
    array (
      0 => 'Not Charged',
    ),
  ),
)
******************************



******************************HOLDING info
array (
  'id' => '148823',
  'holdings_id' => '163239',
  'item_id' => '335374',
  'status' => 'Not Charged',
  'location' => 'Deerfield Periodical Collection',
  'reserve' => 'N',
  'callnumber' => NULL,
  'barcode' => '3600151208272',
  'use_unknown_message' => false,
  'item_sort_seq' => '5',
  'sort_seq' => 9223372036854775807,
  '_fullRow' =>
  array (
    'BIB_ID' => '148823',
    'MFHD_ID' => '163239',
    'ITEM_BARCODE' => '3600151208272',
    'ITEM_ID' => '335374',
    'ON_RESERVE' => 'N',
    'ITEM_SEQUENCE_NUMBER' => '5',
    'RECALLS_PLACED' => '0',
    'HOLDS_PLACED' => '0',
    'STATUS' => 'Not Charged',
    'RECORD_SEGMENT' => '00324cy  a22001333  450000100070000000400070000700500170001400800330003185200150006486600230007986600260010286600340012886600280016216323914882320120427104135.09807285p    8   4001baeng0000000  bPERIODICAL4080av.1:no.1 (1959)4080av.2-51 (1960-2009)4080xSubscription canceled 20094080xLDR updated 06/23/10',
    'ITEM_ENUM' => 'v.46',
    'LOCATION' => 'Deerfield Periodical Collection',
    'TEMP_LOCATION' => '0',
    'PERM_LOCATION' => '41',
    'CALLNUMBER' => NULL,
    'DUEDATE' => NULL,
    'RETURNDATE' => NULL,
    'SORT_SEQ' => NULL,
    'ITEM_TYPE_ID' => '1',
    'TEMP_ITEM_TYPE_ID' => '0',
    'STATUS_ARRAY' =>
    array (
      0 => 'Not Charged',
    ),
  ),
)
******************************



******************************HOLDING info
array (
  'id' => '148823',
  'holdings_id' => '163239',
  'item_id' => '319871',
  'status' => 'Not Charged',
  'location' => 'Deerfield Periodical Collection',
  'reserve' => 'N',
  'callnumber' => NULL,
  'barcode' => '3600151229133',
  'use_unknown_message' => false,
  'item_sort_seq' => '6',
  'sort_seq' => 9223372036854775807,
  '_fullRow' =>
  array (
    'BIB_ID' => '148823',
    'MFHD_ID' => '163239',
    'ITEM_BARCODE' => '3600151229133',
    'ITEM_ID' => '319871',
    'ON_RESERVE' => 'N',
    'ITEM_SEQUENCE_NUMBER' => '6',
    'RECALLS_PLACED' => '0',
    'HOLDS_PLACED' => '0',
    'STATUS' => 'Not Charged',
    'RECORD_SEGMENT' => '00324cy  a22001333  450000100070000000400070000700500170001400800330003185200150006486600230007986600260010286600340012886600280016216323914882320120427104135.09807285p    8   4001baeng0000000  bPERIODICAL4080av.1:no.1 (1959)4080av.2-51 (1960-2009)4080xSubscription canceled 20094080xLDR updated 06/23/10',
    'ITEM_ENUM' => 'v.45',
    'LOCATION' => 'Deerfield Periodical Collection',
    'TEMP_LOCATION' => '0',
    'PERM_LOCATION' => '41',
    'CALLNUMBER' => NULL,
    'DUEDATE' => NULL,
    'RETURNDATE' => NULL,
    'SORT_SEQ' => NULL,
    'ITEM_TYPE_ID' => '1',
    'TEMP_ITEM_TYPE_ID' => '0',
    'STATUS_ARRAY' =>
    array (
      0 => 'Not Charged',
    ),
  ),
)
******************************



******************************HOLDING info
array (
  'id' => '148823',
  'holdings_id' => '163239',
  'item_id' => '238742',
  'status' => 'Not Charged',
  'location' => 'Deerfield Periodical Collection',
  'reserve' => 'N',
  'callnumber' => NULL,
  'barcode' => '3600151072265',
  'use_unknown_message' => false,
  'item_sort_seq' => '7',
  'sort_seq' => 9223372036854775807,
  '_fullRow' =>
  array (
    'BIB_ID' => '148823',
    'MFHD_ID' => '163239',
    'ITEM_BARCODE' => '3600151072265',
    'ITEM_ID' => '238742',
    'ON_RESERVE' => 'N',
    'ITEM_SEQUENCE_NUMBER' => '7',
    'RECALLS_PLACED' => '0',
    'HOLDS_PLACED' => '0',
    'STATUS' => 'Not Charged',
    'RECORD_SEGMENT' => '00324cy  a22001333  450000100070000000400070000700500170001400800330003185200150006486600230007986600260010286600340012886600280016216323914882320120427104135.09807285p    8   4001baeng0000000  bPERIODICAL4080av.1:no.1 (1959)4080av.2-51 (1960-2009)4080xSubscription canceled 20094080xLDR updated 06/23/10',
    'ITEM_ENUM' => 'v.42',
    'LOCATION' => 'Deerfield Periodical Collection',
    'TEMP_LOCATION' => '0',
    'PERM_LOCATION' => '41',
    'CALLNUMBER' => NULL,
    'DUEDATE' => NULL,
    'RETURNDATE' => NULL,
    'SORT_SEQ' => NULL,
    'ITEM_TYPE_ID' => '1',
    'TEMP_ITEM_TYPE_ID' => '0',
    'STATUS_ARRAY' =>
    array (
      0 => 'Not Charged',
    ),
  ),
)
******************************
[tiu_example.txt](https://github.com/CARLI/vufind/files/1112655/tiu_example.txt)

**Comment by gibsonjc** [comment]
Yes, I agree, go ahead and do what you suggested ("The easiest "solution" to this problem is to simply remove the "Copy 0" labels from the display (these numbers are simply enumerated, i.e., they don't come from the holdings data).") and let's see what that looks like.  Seems like it can't be worse!

**Comment by gibsonjc** [comment]
ISU - major concern that Milner Library has before making a switch to VuFind3.  ISU would prefer no copy number display, particularly the “0” and duplicate #’s

**Comment by gibsonjc** [comment]
LFC - “Copy 0” is very confusing.  Can it be removed?

**Comment by gibsonjc** [comment]
WHE - We have two copies, copy 1 and copy 2 of Letters by Saint Ambrose. In VuFind, they display properly as copy 1 and copy 2:

https://vufind.carli.illinois.edu/vf-whe/Record/whe_27108

In VuFind3, they display incorrectly as copy 1 and copy 1:

https://vufind3.carli.illinois.edu/vf-whe/Record/WHEdb.27108

**Comment by gibsonjc** [comment]
MON - 12/14/2017 open call

**Comment by gibsonjc** [comment]
KIS - KIS - For some reason the item that is shown (Cambridge companion to crime fiction) is  showing [...] that the copy is 0 in the new VU find. Our item record shows that we have copy 1 [...]

Example:
https://vufind4.carli.illinois.edu/vf-kis/Search/Results?lookfor=cambridge+companion+to+crime+fiction&type=AllFields&limit=20&sort=relevance
https://vufind4.carli.illinois.edu/vf-kis/Record/KISdb.110020

**Comment by gibsonjc** [comment]
EIU - 12/15/2017 open call - display real copy number

**Comment by cedelis** [comment]
Here's the SQL that the Voyager driver (parent class of VoyagerRestful) uses to collect data for Holdings information in the Detailed Record page (e.g., https://i-share-test.carli.illinois.edu/vf-sie/Record/SIEdb.374518 ):

SELECT BIB_ITEM.BIB_ID, MFHD_ITEM.MFHD_ID, ITEM_BARCODE.ITEM_BARCODE, ITEM.ITEM_ID, ITEM.ON_RESERVE, ITEM.ITEM_SEQUENCE_
NUMBER, ITEM.RECALLS_PLACED, ITEM.HOLDS_PLACED, ITEM_STATUS_TYPE.ITEM_STATUS_DESC as status, MFHD_DATA.RECORD_SEGMENT, M
FHD_ITEM.ITEM_ENUM, NVL(LOCATION.LOCATION_DISPLAY_NAME, LOCATION.LOCATION_NAME) as location, ITEM.TEMP_LOCATION, ITEM.PE
RM_LOCATION, MFHD_MASTER.DISPLAY_CALL_NO as callnumber, to_char(CIRC_TRANSACTIONS.CURRENT_DUE_DATE, 'MM-DD-YY') as dueda
te, CASE WHEN ITEM_STATUS_TYPE.ITEM_STATUS_DESC = 'Discharged' THEN (
  SELECT TO_CHAR(MAX(CIRC_TRANS_ARCHIVE.DISCHARGE_DATE), 'MM-DD-YY HH24:MI')
    FROM SIEDB.CIRC_TRANS_ARCHIVE
    WHERE CIRC_TRANS_ARCHIVE.ITEM_ID = ITEM.ITEM_ID
) ELSE NULL END RETURNDATE, ITEM.ITEM_SEQUENCE_NUMBER, (SELECT SORT_GROUP_LOCATION.SEQUENCE_NUMBER FROM SIEDB.SORT_GROUP
, SIEDB.SORT_GROUP_LOCATION WHERE SORT_GROUP.SORT_GROUP_DEFAULT = 'Y' AND SORT_GROUP_LOCATION.SORT_GROUP_ID = SORT_GROUP
.SORT_GROUP_ID AND SORT_GROUP_LOCATION.LOCATION_ID = ITEM.PERM_LOCATION) SORT_SEQ, ITEM.ITEM_TYPE_ID, ITEM.TEMP_ITEM_TYP
E_ID FROM SIEDB.BIB_ITEM, SIEDB.ITEM, SIEDB.ITEM_STATUS_TYPE, SIEDB.ITEM_STATUS, SIEDB.LOCATION, SIEDB.MFHD_ITEM, SIEDB.
MFHD_MASTER, SIEDB.MFHD_DATA, SIEDB.CIRC_TRANSACTIONS, SIEDB.ITEM_BARCODE WHERE BIB_ITEM.BIB_ID = 374518 AND BIB_ITEM.IT
EM_ID = ITEM.ITEM_ID AND ITEM.ITEM_ID = ITEM_STATUS.ITEM_ID AND ITEM_STATUS.ITEM_STATUS = ITEM_STATUS_TYPE.ITEM_STATUS_T
YPE AND ITEM_BARCODE.ITEM_ID (+)= ITEM.ITEM_ID AND LOCATION.LOCATION_ID = ITEM.PERM_LOCATION AND CIRC_TRANSACTIONS.ITEM_
ID (+)= ITEM.ITEM_ID AND MFHD_ITEM.ITEM_ID = ITEM.ITEM_ID AND MFHD_MASTER.MFHD_ID = MFHD_ITEM.MFHD_ID AND MFHD_DATA.MFHD
_ID = MFHD_ITEM.MFHD_ID AND MFHD_MASTER.SUPPRESS_IN_OPAC='N' ORDER BY ITEM.ITEM_SEQUENCE_NUMBER, MFHD_DATA.MFHD_ID, MFHD
_DATA.SEQNUM

Can someone come up with a better query that pulls more accurate copy number information? Currently VuFind treats ITEM_ENUM as "copy number."

If not, then I suppose I could simply remove the incorrect copy number and only show the volume info (which is sometimes absent), E.g, instead of displaying this:

Copy 30 (1975 (v.35)) |	Available | Request Item

we can instead display something like:

1975 (v.35) | Available | Request Item

Do keep in mind that for those occasions when volume info is missing, it would look like something this (e.g.,  https://i-share-test.carli.illinois.edu/vf-eiu/Record/EIUdb.1146101 ):

Instead of:

 Copy 0 | Available | Request Item

it would display as:

	Available | Request Item

For the EIUdb.1146101 example above, this doesn't look too bad since there is only one in the list. But, it might look strange with many item listings. Does such a scenario ever exist, though? If so, please share examples! Because it's *very* important to note that in the current (latest, most recent) VuFind interface, we do in fact need to display the list of items, along with the associated  "Request Item" links beside each item, because VuFind needs to know *which* item from the list to actually Request. E.g., Here's an example URL that triggers the Request Item page: https://i-share-test.carli.illinois.edu/vf-sie/Record/SIEdb.374518/ILLRequest?holdings_id=405426&item_id=451562&hashKey=[redacted]#tabnav

Notice the item_id=451562 parameter? That is necessary. I.e., In VuFind, the patron selects the item *before* the Request Item page is displayed. (This is different from the old version of VuFind (ver 0.6) where it allows the patron to select the item from a drop-down list in the actual Request Item page itself.)

Chris

**Comment by gibsonjc** [comment]
@cedelis Thanks for this query information and good to know we can tweak it if we want to!

I want to clarify that you say that _Currently VuFind treats ITEM_ENUM as "copy number."_ but I don't think that's true because the MFHD_ITEM.ITEM_ENUM data for SIE BIB 374518 is actually "1975 (v.35)", not "30". The "Copy 30" appears to be some kind of incrementing number that VuFind is building outside of this query; it is not present in the Item data in Voyager.    Can you see where it is doing this?  In the display generation somewhere?

In Voyager the copy number that we'd prefer to display is in the MFHD, which is going to be hard to get at with an sql query because MFHD data do not have their own, easily accessible fields.  As a second choice, there is also a copy number in Voyager in the Item record in ITEM.COPY_NUMBER that we could use (but it is less reliable than the copy number in the MFHD).  I will see if I can get someone to help adjust the sql above to call upon ITEM.COPY_NUMBER for this data if you can help inform us what it needs to be called so that when VuFind builds this display, it will use that instead of whatever magical incrementing it is currently doing.

**Comment by cedelis** [comment]
@gibsonjc , you are correct about ITEM_ENUM not being treated as "copy number." My mistake. (ITEM_ENUM is, in fact, volume.

It's actually ITEM_SEQUENCE_NUMBER

References:

SQL: https://github.com/CARLI/vufind/blob/carli-release-4.1/module/VuFind/src/VuFind/ILS/Driver/Voyager.php#L619 

"copy number" variable assignment: https://github.com/CARLI/vufind/blob/carli-release-4.1/module/VuFind/src/VuFind/ILS/Driver/Voyager.php#L752

Sorry about the confusion.

**Comment by gibsonjc** [comment]
Ah, yes, I can see these ITEM.ITEM_SEQUENCE_NUMBER numbers when I look at the Voyager tables. These control, not surprisingly, which order the Items are displayed in the list in Voyager clients, and can continue to be used for determining the order which the items should display here in VuFind as well, but it is decidedly NOT the copy number information that we want to show.

Is there a way that we can use COPY_NUMBER for making the Copy display instead? Though I don't see ITEM.COPY_NUMBER in any of the queries in this file already so it would probably need to be added.

Using COPY_NUMBER would be preferable to hiding it altogether, but hiding altogether it is better than using ITEM_SEQUENCE_NUMBER !

**Comment by cedelis** [comment]
@gibsonjc I made the change to DEVEL (compare  https://i-share-devel.carli.illinois.edu/vf-whe/Record/WHEdb.27108  vs. https://i-share.carli.illinois.edu/vf-whe/Record/WHEdb.27108 , which has two "Copy 1"s).

Could the solution really be this simple? :-) Great catch! I wonder if others using the Voyager (and/or VoyagerRestful) driver never noticed this? And/or did they almost always have only one copy of something? In any case, if this is indeed the solution, I can submit a pull request to the main github repo so others can benefit.

**Comment by cedelis** [comment]
Ready for Testing

**Comment by gibsonjc** [comment]
This fix at least uses a predictable piece of information now to display after the word Copy: the copy number as found in the Voyager Item Record.  It isn't our ideal, which would be the copy number as found in the MFHD 852 $t, but it is a major improvement, so let's move this to Production!

**Comment by cedelis** [comment]
In prod
