### ISSUE TITLE
No I-Share view

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/vufind#17]
JIRA issue created by: Jessica Gibson (gibsonjc)
Originally opened: 2016-01-28 09:42 AM

There isn't an equivalent to http://vufind.carli.illinois.edu/all/vf/ that is branded as I-Share or indicates it is the union catalog.

Currently in production, the http://vufind.carli.illinois.edu/all/vf/ url goes straight to I-Share. The page with the institution dropdown list is https://i-share.carli.illinois.edu/ilcso/cgi-bin/welcome . 

In vufind2, /all/vf/ goes to the institution dropdown page https://vufind2.carli.illinois.edu/all/vf/

**Comment by gibsonjc** [comment]
Because of the way that the records are indexed in Solr, it is not a straightforward thing to duplicate what we have with VuFind 0.6.  

VuFind2 is set up with many instances, but there are TWO types of catalogs:
    * one for each library's LOCAL catalog, e.g., https://vufind2-test.carli.illinois.edu/vf-mil
    * one for each library's view of the shared catalog ("UC"), e.g., https://vufind2-test.carli.illinois.edu/all/vf-mil

However, VuFind2 is set up with a single Solr server (indexed MARC records).  The LOCAL catalog and the UC instances are each configured to search the Solr server DIFFERENTLY so that the LOCAL catalog serves up only local records, while the UC serves up deduplicated records (from all libraries' catalogs).

We will not be attempting to change this at this time.
