### ISSUE TITLE
Filters retained during switch from Local to I-Share catalog

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#184]
The "Retain current filters" checkbox stays checked during a switch from the local to the I-Share catalog. This can be great for limits like format, but limits for a local shelving location can surprise when there are no results.

Not sure if a problem, or only something to be aware of.

![bookstacksfilterretainedonceswitchtoi-sharecatalog](https://cloud.githubusercontent.com/assets/20848151/26644489/715782a4-45fa-11e7-8ce5-bbcbfdefa0e1.PNG)

**Comment by bbwalter** [comment]
We just implemented New VuFind this month (August 2018), and I was wondering why my Public Services people were complaining about this issue. My testing has shown that it happens with Chrome, but not Edge or Firefox.

**Comment by cedelis** [comment]
I have confirmed this behavior. This would require a javascript solution that when triggered by a catalog change would strip out the filter parameters.

**Comment by gibsonjc** [comment]
After doing a bit more testing, what MBI is reporting on RT 101316 is not just that the "Retain current filters" stays checked _by default_ when moving from local to I-Share--that is true--but if the user realizes that the box "Retain current filters" is checked by default and purposefully UNchecks it before rerunning the search in the I-Share catalog, the filters are usually retained anyway.

It happened to me when testing in Windows 10 Chrome and Firefox but not Microsoft Edge, and on Mac Chrome and Firefox. (Mac Safari won't even let me rerun the search in I-Share when I change that dropdown which is a completely different problem!  EDIT: opened Issue #374 about this)

Replication steps:
(Some browsers seem to remember if you have unchecked the "Retain current filters" box before during the session already or not, so restart your browser to clear that memory when testing.)
1. Do search in local catalog : (searched for cat) 
https://i-share.carli.illinois.edu/vf-mbi/Search/Results?lookfor=cat&type=AllFields
2. Narrow search : (to location Michigan) 
https://i-share.carli.illinois.edu/vf-mbi/Search/Results?lookfor=cat&type=AllFields&filter%5B%5D=collection%3A%22MBIdb_group_Michigan%22
3. Change catalog dropdown to I-Share and UNcheck "Retain current filters" and click Find: (but filters are retained anyway)
https://i-share.carli.illinois.edu/all/vf-mbi/Search/Results?lookfor=cat&type=AllFields&filter%5B%5D=collection%3A%22MBIdb_group_Michigan%22&limit=20&sort=relevance

**Comment by cedelis** [comment]
In TEST, I resolved the issue of unchecking "Retain current filters" not being recognized when switching from local catalog to I-Share catalog (see below in "Replication steps").

However, as per the original issue, do we want to automatically (forcefully) remove certain filters when switching between local and I-Share catalogs? I suppose when switching from local to I-Share, the "Location" facet should probably be removed since that will (almost?) always yield empty search results. And when switching from I-Share to local, do we want to remove the "Institution" filter? Are there any more filters we need to manipulate?

Replication steps:
(Some browsers seem to remember if you have unchecked the "Retain current filters" box before during the session already or not, so restart your browser to clear that memory when testing.)

Do search in local catalog : (searched for cat)
https://i-share-test.carli.illinois.edu/vf-mbi/Search/Results?lookfor=cat&type=AllFields
Narrow search : (to location Michigan)
https://i-share-test.carli.illinois.edu/vf-mbi/Search/Results?lookfor=cat&type=AllFields&filter%5B%5D=collection%3A%22MBIdb_group_Michigan%22
Change catalog dropdown to I-Share and UNcheck "Retain current filters" and click Find: (but filters are retained anyway)
https://i-share-test.carli.illinois.edu/all/vf-mbi/Search/Results?lookfor=cat&type=AllFields&filter%5B%5D=collection%3A%22MBIdb_group_Michigan%22&limit=20&sort=relevance

**Comment by cedelis** [comment]
I've added the following actions (also in TEST): 

    When switching from local to I-Share, the "Location" facet is removed.
    When switching from I-Share to local, the "Institution" filter is removed.

**Comment by gibsonjc** [comment]
All of these changes look good in my testing in various scenarios and browsers!  Ready for Prod.

**Comment by cedelis** [comment]
In PROD.
