### ISSUE TITLE
Default Reserve location and status language is not appropriate for all libraries

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#191]
ADL - title: "Feedback that sticks : the art of communicating neuropsychological assessment results"  On the results page, the books is listed as being Available… well… yes, it is.  To our Vancouver campus users.  Here in Chicago, our copy is checked out, but you can’t see that until you click on the title for more information.

![screen shot 2017-06-06 at 11 07 25 am](https://user-images.githubusercontent.com/17598357/26839869-ed0a8078-4aa9-11e7-883c-ea5b57478098.png)

https://vufind3.carli.illinois.edu/vf-adl/Search/Results?lookfor=Feedback+that+sticks+%3A+the+art+of+communicating+neuropsychological+assessment+results&type=Title&limit=20&sort=relevance

Also the “Ask at Circulation” would only work at our Chicago location.  In Vancouver that instruction wouldn’t make sense to users because of the way they have things set up there.  I’m not sure where that text is coming from, so I’m not sure if that’s something I could change on my end or not.

![screen shot 2017-06-06 at 11 15 04 am](https://user-images.githubusercontent.com/17598357/26839898-fae31f70-4aa9-11e7-85b9-b8820783a56d.png)

**Comment by gibsonjc** [comment]
Another example: https://vufind3-test.carli.illinois.edu/vf-adl/Search/Results?lookfor=the+great+ideas+of+clinical+science++17+principles&type=Title&limit=20&sort=relevance

**Comment by gibsonjc** [comment]
in /languages/en.ini:

On Reserve = "On Reserve"
On Reserve - Ask at Circulation Desk = "On Reserve - Ask at Circulation Desk"
on_reserve = "Reserves - Ask at Circulation"

**Comment by dmcmpbll** [comment]
MIL - RT100421

MIL uses the "Reserves" method for managing a display/new books list: 
https://www.carli.illinois.edu/products-services/i-share/circ/secure/DisplayLocation 

They report that:
"On the one hand, it is nice that the new VF displays the message "On reserve- ask at circulation desk" when the item is an actual course reserve. Much clearer and noticeable, we think. However, it causes a problem for our new books, because they are not actually on reserve at circulation desk. They are in the new book shelving area, and we are only using the reserve function in Voyager as a work around so we don't have to have our cataloger edit a bunch of records every month when things cycle off that location.
We're worried this will cause patron confusion. Any suggestions? Is there a way to have that message be different if the location of the reserve list is different? The location of course reserves lists we have as "reserves," while the location of new books list is fixed as "new books.""

Example items at MIL:
For example, old VF display of course reserve item: https://vufind.carli.illinois.edu/vf-mil/Record/mil_459373
Old Vf display of new book shelf item: https://vufind.carli.illinois.edu/vf-mil/Record/mil_459726
New VF display of course reserve item: https://i-share.carli.illinois.edu/vf-mil/Record/MILdb.459373
New VF display of new book shelf item: https://i-share.carli.illinois.edu/vf-mil/Record/MILdb.459726

**Comment by gibsonjc** [comment]
in /languages/en.ini:
let's change 

On Reserve - Ask at Circulation Desk = "On Reserve - Ask at Circulation Desk"
on_reserve = "Reserves - Ask at Circulation"

to

On Reserve - Ask at Circulation Desk = "On Reserve"
on_reserve = "Reserves"

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Reserves wording looks good, ready for Prod!

**Comment by cedelis** [comment]
In PROD
