### ISSUE TITLE
no option to “request item” until/unless you are logged in is confusing

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#215]
ONU - I do NOT like how (seemingly) there is no option to “request item” until/unless you are logged in.  Most people searching the catalog are not logged in so it will be very confusing for them to not see an option to request the item.  (Currently, when one clicks on “request item” it takes them to the login page; we like this)

ONU - There is no request option without signing in. It does not prompt you anywhere that you must log in to request so I see many patrons just thinking there is no request option and giving up.

ONU - [main objection 1: RT 89510] Need to login before getting the Request option. We like hitting Request then getting the login prompt.

**Comment by gibsonjc** [comment]
MIL - Things we view as obstacles to adopting VF3--Request tab:  I wasn’t able to see the option to request an item either in the local or union catalog until I was logged in.  I found that confusing.

**Comment by slknight** [comment]
EIU has been discussing this over Email. Majority opinion is that request should be visible regardless of login status.

**Comment by gibsonjc** [comment]
BRA - ...on the see-no-request-until-after-login
issue. We all agree that it is important to see request link without login
and that Bradley would not switch to a new VuFind before this is resolved.

**Comment by gibsonjc** [comment]
@cedelis I see this was marked Ready for Testing but no comment was made so an email was not sent out so I didn't know it was here.  Is this on DEVEL and TEST?  I think that's where I see it.  (But we can't currently test it on DEVEL.)

**Comment by cedelis** [comment]
@gibsonjc I'll try to remember to also add a comment next time. sorry. It's on both TEST and DEVEL.

**Comment by gibsonjc** [comment]
Open call 12/15/2017: 
UIC -
EIU - 
JUD - 
LFC -
CSC -
MRT -

**Comment by gibsonjc** [comment]
I was able to do some basic testing tonight as myself and it seemed to work correctly by prompting me to log in and then either initiating the request or telling me I didn't have sufficient privs to place the request.   I'd appreciate it if others could do testing with additional libraries.  I also think we should retest specifically for libraries that do not allow local requesting to make sure this hasn't circumvented what was put in place to stop that before. @dgree1 @dmcmpbll

**Comment by slknight** [comment]
I am seeing the request button when not logged in to TEST

![image](https://user-images.githubusercontent.com/15163837/34211284-34b7ca9e-e55e-11e7-8803-0a9053838a01.png)

Clicking request invokes LOGIN. 

Request window pops up after login with appropriate pickup location.

Place request works.

Cancel request works.

All appears to work as expected.

**Comment by slknight** [comment]
John Whisler checked this in TEST and it also worked as expected for him. 

"I tried it in test and it seemed to work just fine.  I didn’t actually place the request, but it gave me the request button in the bib display, and clicking it prompted me to enter my barcode and name, gave me the pickup location options and the Place Request button.  So it looks good to me.

--jw
"

**Comment by slknight** [comment]
I'm not seeing a request link for items that are held locally but not available. Is that supposed to be working?

![image](https://user-images.githubusercontent.com/15163837/34215453-fc6d88d8-e56a-11e7-8187-09ea2f885d42.png)

**Comment by slknight** [comment]
Request is not suppressed for locally held available items

![image](https://user-images.githubusercontent.com/15163837/34215535-380bdce6-e56b-11e7-932d-709ff0afdb66.png)

**Comment by dgree1** [comment]
from Denise and Debbie-
Regarding    " I also think we should retest specifically for libraries that do not allow local requesting to make sure this hasn't circumvented what was put in place to stop that before. @dgree1 @dmcmpbll"

We did several tests in DOM-test. For libraries that don't allow local call slip the request item link is showing both when logged in and when not.  Here's screen shot from https://i-share-test.carli.illinois.edu/vf-dom/Record/DOMdb.50028

![dom_test_not_loggedin](https://user-images.githubusercontent.com/29785703/34231130-605b4a3a-e5a0-11e7-9ff4-3d8e8bd3128c.GIF)

Currently in new VuFind4 prod the request link is not showing (as expected since DOM doesn't allow local call slip.) See https://i-share.carli.illinois.edu/vf-dom/Record/DOMdb.50028

**Comment by dmcmpbll** [comment]
Update: We know that the steps being worked on in this ticket to make the "Request item" show when the patron is not logged in, are affecting the setup that had previously been set in https://github.com/CARLI/vufind/issues/59 to only show the "Request item" link when the library allowed local call slip requesting.

**Comment by cedelis** [comment]
Another Update: I *think* I have fixed Issue #59 that got reintroduced in this issue.

**Comment by slknight** [comment]
Checked several records in different locations for EIU in TEST and did not see the Request link for locally held items.

**Comment by dmcmpbll** [comment]
Yes, the fix for 59 appears to have worked, while keeping the link displaying while not logged in (fix for this ticket, 215).

@dgree1 - are your tests the same?
Denise, if your tests also work as expected, I'd think this means ready for prod (both issues- 215 and fix for 59).

Examples with screenshots:
For DOM-local on test; not logged in: link does not show.
For DOM-local on test, logged in: link does not show.
(same screenshot for both, since looked the same for both scenarios above)
![image](https://user-images.githubusercontent.com/20848151/34269640-ce1653c6-e64a-11e7-9801-90ed1cfba47a.png)

For DOM-I-Share on test, logged in: link does not show for DOM book; does show for other libs.
![image](https://user-images.githubusercontent.com/20848151/34269618-afac30fe-e64a-11e7-9265-be35dbf698ef.png)

For UIU-local on test; not logged in: link shows.
For UIU-local on test, logged in: link shows.
(same screenshot for both, since same for both scenarios)
![image](https://user-images.githubusercontent.com/20848151/34269699-fde66c80-e64a-11e7-937c-3cb2ca4827c5.png)

For UIU-I-Share on test; logged in: link shows.
![image](https://user-images.githubusercontent.com/20848151/34269791-429e3e02-e64b-11e7-8920-76a32296c7ac.png)

**Comment by dgree1** [comment]
My tests were the same. 
For UIU-test, request link show both NOT logged in and logged in. 

For CTU-test, 
The historical setting of the Old Testament /
https://i-share-test.carli.illinois.edu/vf-ctu/Record/CTUdb.22151
no request , not logged in

![ctu_test_not_logged in](https://user-images.githubusercontent.com/29785703/34274891-5a8c532c-e660-11e7-8b96-2f37974f2e43.GIF)


no request, logged in.


![ctu_test_logged in](https://user-images.githubusercontent.com/29785703/34274899-687440bc-e660-11e7-89bd-c9342b1dcbf9.GIF)

**Comment by dmcmpbll** [comment]
Seems ready for prod, @cedelis 
(both issues- 215 and fix for 59).
