### ISSUE TITLE
Multiple MFHDs are grouping together in display

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#246]
Moved details on this from #192 where it was first discovered:

https://vufind3-devel.carli.illinois.edu/vf-whe/Record/WHEdb.316400

JG: In this example, I do NOT understand why it is grouping seven of these together and showing one alone making them look like two MFHDs (one with seven one with one). I also do NOT understand why if I add an ninth MFHD, the display of these changes yet again (eight are together and one is alone, but it is a different one!).

CD: OK, I believe I have fixed the grouping issue (of why the 8 MFHDs weren't showing up together, instead of being split into 7 and 1).

JG: When there are eight MFHDs in Voyager, I would actually expect to see eight individual entries for Location + Call number + link (one for each).  You did fix the grouping issue that I saw so that one is not randomly called out on its own, but my real question is: why is the system artificially grouping the MFHDs together for display at all?  What criteria is it using to do that?  I'm not sure we want it to do that, but I'm willing to understand it better before I condemn it!

**Comment by cedelis** [comment]
@gibsonjc , VuFind is currently designed to group by MFHD's location: 

https://github.com/CARLI/vufind/blob/release-3.0/module/VuFind/src/VuFind/ILS/Logic/Holds.php#L104 


So, this appears to be according to the design of VuFind (i.e., nothing new here; this is how it's been working all along).

I'll cut and paste the comments here (link to source code is above):

    /**
     * Support method to rearrange the holdings array for displaying convenience.
     *
     * @param array $holdings An associative array of location => item array
     *
     * @return array          An associative array keyed by location with each
     * entry being an array with 'notes', 'summary' and 'items' keys.  The 'notes'
     * and 'summary' arrays are note/summary information collected from within the
     * items.
     */

**Comment by cedelis** [comment]
@gibsonjc In replying to your following comment:

"JG: When there are eight MFHDs in Voyager, I would actually expect to see eight individual entries for Location + Call number + link (one for each). You did fix the grouping issue that I saw so that one is not randomly called out on its own, but my real question is: why is the system artificially grouping the MFHDs together for display at all? What criteria is it using to do that? I'm not sure we want it to do that, but I'm willing to understand it better before I condemn it!"

Please take a look at this record in the old version of vufind: https://vufind.carli.illinois.edu/vf-whe/Record/whe_316400 and also I-Share (webvoyage): https://i-share.carli.illinois.edu/whe/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=316400

You will notice that there is only one entry for Location + Call Number. Also, you will notice that there are no E-Resource links whatsoever.

Can you find a better example that illustrates this issue more clearly?

Thanks

**Comment by gibsonjc** [comment]
Multiple MFHDs are no longer grouping together in display. Ready for prod.

**Comment by cedelis** [comment]
In prod, commit 11733f3d120a2737f84847b6fd3f8e98222f0355
