### ISSUE TITLE
Course Reserves search results do not indicate which course or instructor

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#252]
LFC - For Course Reserves, the course that the item is on reserve for isn’t displaying [in the results list].  Compare: 
https://vufind3.carli.illinois.edu/vf-lfc/Search/Reserves?course=&inst=380&submit=Find&dept= 
And 
https://vufind.carli.illinois.edu/vf-lfc/Search/Reserves?course=&inst=380&dept=&submit=Find

**Comment by gibsonjc** [comment]
NPU - it would be great to see the course information within the reserve list display.  Displaying the course and instructor information on the results page would be very helpful.

**Comment by nmswanson** [comment]
ISU would prefer course and/or Instructor were listed on Course Reserve results page.

4/19/18 email

**Comment by nmswanson** [comment]
LFC-  In the old VuFind, if you look up reserves by professor, it would designate which item was on reserve for which course. This was very useful for students, as many of them don't know their course number, but do know their professor's name. (Example)<[https://vufind.carli.illinois.edu/vf-lfc/Search/Reserves?course=&inst=570&dept=&submit=Find](https://vufind.carli.illinois.edu/vf-lfc/Search/Reserves?course=&inst=570&dept=&submit=Find)>

In the new VuFind, it lists the books for all the professor's courses, without any indication of which books go with which courses, making it unhelpful. (Example<[https://i-share.carli.illinois.edu/vf-lfc/Search/Reserves?course=&inst=570&submit=Find&dept=](https://i-share.carli.illinois.edu/vf-lfc/Search/Reserves?course=&inst=570&submit=Find&dept=)>)

In addition, the display of course reserves in the old VuFind was also better. It was clear and uncluttered. Course reserves in the new VuFind contain more information than students are looking for and is confusing.

RT101628

**Comment by cedelis** [comment]
Currently, we are using the default "Course Reserves" setup, called "Driver-Based Reserves" (see: https://vufind.org/wiki/configuration:course_reserves#driver-based_reserves_default ). This search relies on realtime lookups via the Voyager ILS driver (runs SQL against Voyager tables, basically), the results of which are rather simplistic: the bib IDs are returned from the ILS driver, which are then used to simply show a standard results list (similar to a "Simple Search" and "Advanced Search"). This results list does *not* include information about instructor or course.

In order to obtain instructor and course information and integrate it into our search results, we would need to switch to a "Solr-Based Reserves" set up (https://vufind.org/wiki/configuration:course_reserves#solr-based_reserves ). This would require us to setup nightly export scripts to extract this information from Voyager (VuFind includes a command-line export utility), and then also index this data into Solr (also, nightly).

**Comment by cedelis** [comment]
@gibsonjc I have a pilot on DEVEL for all local catalogs. It is pretty well isolated, therefore it should remain fairly stable while I work on other issues. Have a look when you get the chance. Thanks

**Comment by cedelis** [comment]
Now in TEST

**Comment by cedelis** [comment]
@gibsonjc The initial Course Reserves page now sorts by Course by default. And the ultimate search results page now sorts by Title

**Comment by gibsonjc** [comment]
At our meeting on 10/18 we discussed the new format of reserves data that is needed for this new Course Reserves method, including when one or more of the fields is null.  Gordon changed the query that produces the data file accordingly. Sorting defaults look good!  Next we'll try to change the text on the page:

**Search For Items on Reserve**
to
**Course Reserves**

And

**Your search terms**
to
**Search for Instructor, Course, or Department:**

**Comment by cedelis** [comment]
@gibsonjc Label changes are now in TEST.

**Comment by cedelis** [comment]
In PROD
