### ISSUE TITLE
Course Reserves showing inactive lists

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#258]
NPU - It seems like VuFind3 is pulling information from both active and inactive course reserve lists. For example, the course "AMUS 1300: Violin" comes up in the VuFind3 search but the corresponding list was set to expire in 2015 and the item is not "on reserve.

https://vufind3.carli.illinois.edu/vf-npu/Search/Reserves
<Choose AMUS 1300>
https://vufind3.carli.illinois.edu/vf-npu/Search/Reserves?course=1033&submit=Find&inst=&dept=
(compare to https://vufind.carli.illinois.edu/vf-npu/Search/Reserves)

Course Reserves should only courses, instructors, and departments with active lists.

**Comment by dmcmpbll** [comment]
This persists in VuFind4.
Course Reserves is showing lists with in-active dates.

The status of the items on the list does not determine whether the list shows or not (whether the item is turned ON for reserves or OFF for reserves has no effect). Lists with no items show: https://i-share-test.carli.illinois.edu/vf-mil/Search/Reserves?course=703&submit=Find&inst=&dept= 

To navigate to link above:
https://i-share-test.carli.illinois.edu/vf-mil/Search/Reserves
 select the course DA 102: Tap I

**Comment by cedelis** [comment]
This was tested and put into production today. After tonight's record updates, this issue should be resolved (early tomorrow).

**Comment by cedelis** [comment]
Here's an example to test/verify (a Course Reserves bib that is OPAC suppressed):

Accessible: https://i-share-test.carli.illinois.edu/vf-uic/Record/UICdb.3713223

But not searchable: https://i-share-test.carli.illinois.edu/vf-uic/Search/Results?lookfor=%22CYN+531+ERes+Website%22&type=AllFields&limit=20&sort=relevance

**Comment by cedelis** [comment]
Today, on PROD:

Accessible: https://i-share.carli.illinois.edu/vf-uic/Record/UICdb.3713223

But *IS* (incorrectly) searchable: https://i-share.carli.illinois.edu/vf-uic/Search/Results?lookfor=%22CYN+531+ERes+Website%22&type=AllFields&limit=20&sort=relevance

Tomorrow, on PROD, it should be:

Accessible: https://i-share.carli.illinois.edu/vf-uic/Record/UICdb.3713223

But not searchable: https://i-share.carli.illinois.edu/vf-uic/Search/Results?lookfor=%22CYN+531+ERes+Website%22&type=AllFields&limit=20&sort=relevance

**Comment by cedelis** [comment]
The relevant SQL for this issue is presented below. Can someone make them more accurate?

## There are 3 SQL used to populate the drop down lists for Course, Instructor, and Department

### Course:


<code>
select COURSE.COURSE_NUMBER || \\\': \\\' || COURSE.COURSE_NAME as NAME, COURSE.COURSE_ID from MILDB.RESERVE_LIST, MILDB.RESERVE_LIST_COURSES, MILDB.COURSE where RESERVE_LIST.RESERVE_LIST_ID = RESERVE_LIST_COURSES.RESERVE_LIST_ID and RESERVE_LIST_COURSES.COURSE_ID = COURSE.COURSE_ID group by COURSE.COURSE_ID, COURSE_NUMBER, COURSE_NAME order by COURSE_NUMBER
</code>


### Instructor:


<code>
select INSTRUCTOR.INSTRUCTOR_ID, INSTRUCTOR.LAST_NAME || \\\', \\\' || INSTRUCTOR.FIRST_NAME as NAME from MILDB.RESERVE_LIST, MILDB.RESERVE_LIST_COURSES, MILDB.INSTRUCTOR where RESERVE_LIST.RESERVE_LIST_ID = RESERVE_LIST_COURSES.RESERVE_LIST_ID and RESERVE_LIST_COURSES.INSTRUCTOR_ID = INSTRUCTOR.INSTRUCTOR_ID group by INSTRUCTOR.INSTRUCTOR_ID, LAST_NAME, FIRST_NAME order by LAST_NAME
</code>



### Department:



<code>
select DEPARTMENT.DEPARTMENT_ID, DEPARTMENT.DEPARTMENT_NAME from MILDB.RESERVE_LIST, MILDB.RESERVE_LIST_COURSES, MILDB.DEPARTMENT where RESERVE_LIST.RESERVE_LIST_ID = RESERVE_LIST_COURSES.RESERVE_LIST_ID and RESERVE_LIST_COURSES.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID group by DEPARTMENT.DEPARTMENT_ID, DEPARTMENT_NAME order by DEPARTMENT_NAME
</code>



## Finally, here is the SQL used to act on the choices made from the above 3 criteria:



<code>
select MFHD_MASTER.DISPLAY_CALL_NO, BIB_TEXT.BIB_ID,  BIB_TEXT.AUTHOR, BIB_TEXT.TITLE,  BIB_TEXT.PUBLISHER, BIB_TEXT.PUBLISHER_DATE, subquery.COURSE_ID,  subquery.INSTRUCTOR_ID, subquery.DEPARTMENT_ID  FROM MILDB.BIB_TEXT  JOIN MILDB.BIB_MFHD ON BIB_TEXT.BIB_ID=BIB_MFHD.BIB_ID  JOIN MILDB.MFHD_MASTER  ON BIB_MFHD.MFHD_ID = MFHD_MASTER.MFHD_ID JOIN   (   ((select distinct eitem.mfhd_id, subsubquery1.COURSE_ID,      subsubquery1.INSTRUCTOR_ID, subsubquery1.DEPARTMENT_ID      from MILDB.eitem join     (select distinct reserve_list_eitems.eitem_id,      RESERVE_LIST_COURSES.COURSE_ID,      RESERVE_LIST_COURSES.INSTRUCTOR_ID,      RESERVE_LIST_COURSES.DEPARTMENT_ID from      MILDB.reserve_list_eitems     JOIN MILDB.reserve_list_courses ON       reserve_list_courses.reserve_list_id =       reserve_list_eitems.reserve_list_id      where (RESERVE_LIST_COURSES.COURSE_ID = :course) ) subsubquery1 ON       subsubquery1.eitem_id = eitem.eitem_id)) union   ((select distinct mfhd_item.mfhd_id, subsubquery2.COURSE_ID,     subsubquery2.INSTRUCTOR_ID, subsubquery2.DEPARTMENT_ID     from MILDB.mfhd_item join    (select distinct reserve_list_items.item_id,      RESERVE_LIST_COURSES.COURSE_ID,      RESERVE_LIST_COURSES.INSTRUCTOR_ID,      RESERVE_LIST_COURSES.DEPARTMENT_ID from     MILDB.reserve_list_items    JOIN MILDB.reserve_list_courses on     reserve_list_items.reserve_list_id =     reserve_list_courses.reserve_list_id    where (RESERVE_LIST_COURSES.COURSE_ID = :course)) subsubquery2 ON     subsubquery2.item_id = mfhd_item.item_id ))   ) subquery ON mfhd_master.mfhd_id = subquery.mfhd_id
</code>

**Comment by dmcmpbll** [comment]
I added in the "Having" line which includes a date range based on the "Now" criteria. 
But admittedly, I am unsure if New VuFind uses the "<>Now()" convention.

I am surprised that there were no SQL-coded joins between the tables in the three subqueries.
Should there be joins established in the subqueries?
Example of the table joins I expected to see in the *Course subquery*:
-RESERVE_LIST.RESERVE_LIST_ID=RESERVE_LIST_COURSES.RESERVE_LIST_ID
-RESERVE_LIST_COURSES.COURSE_ID=COURSE.COURSE_ID

I did not add joins into the SQL I've pasted below in case I'm not understanding the syntax that the ||\\\':\\\'|| represents.

------------------------

**Course:**
select COURSE.COURSE_NUMBER || \\\': \\\' || COURSE.COURSE_NAME as NAME, COURSE.COURSE_ID from MILDB.RESERVE_LIST, MILDB.RESERVE_LIST_COURSES, MILDB.COURSE 
where RESERVE_LIST.RESERVE_LIST_ID = RESERVE_LIST_COURSES.RESERVE_LIST_ID 
and RESERVE_LIST_COURSES.COURSE_ID = COURSE.COURSE_ID 
group by COURSE.COURSE_ID, COURSE_NUMBER, COURSE_NAME 
_HAVING (((RESERVE_LIST.EFFECT_DATE)<Now()) AND ((RESERVE_LIST.EXPIRE_DATE)>Now()))_
order by COURSE_NUMBER

**Instructor:**
 select INSTRUCTOR.INSTRUCTOR_ID, INSTRUCTOR.LAST_NAME || \\\', \\\' || INSTRUCTOR.FIRST_NAME as NAME 
from MILDB.RESERVE_LIST, MILDB.RESERVE_LIST_COURSES, MILDB.INSTRUCTOR 
where RESERVE_LIST.RESERVE_LIST_ID = RESERVE_LIST_COURSES.RESERVE_LIST_ID 
and RESERVE_LIST_COURSES.INSTRUCTOR_ID = INSTRUCTOR.INSTRUCTOR_ID 
group by INSTRUCTOR.INSTRUCTOR_ID, LAST_NAME, FIRST_NAME 
_HAVING (((RESERVE_LIST.EFFECT_DATE)<Now()) AND ((RESERVE_LIST.EXPIRE_DATE)>Now()))_
order by LAST_NAME 

**Department:**
select DEPARTMENT.DEPARTMENT_ID, DEPARTMENT.DEPARTMENT_NAME 
from MILDB.RESERVE_LIST, MILDB.RESERVE_LIST_COURSES, MILDB.DEPARTMENT 
where RESERVE_LIST.RESERVE_LIST_ID = RESERVE_LIST_COURSES.RESERVE_LIST_ID 
and RESERVE_LIST_COURSES.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID 
group by DEPARTMENT.DEPARTMENT_ID, DEPARTMENT_NAME 
_HAVING (((RESERVE_LIST.EFFECT_DATE)<Now()) AND ((RESERVE_LIST.EXPIRE_DATE)>Now()))_
order by DEPARTMENT_NAME 

(It appears to me upon first review that the SQL "used to act on the choices made from the above 3 criteria" does not need the date limits added to it as well, since it is calling on those subqueries. Would you agree?)

**Comment by cedelis** [comment]
In DEVEL...

I've added the following constraints to the getCourses(), getInstructors(), and getDepartment() queries in VuFind DEVEL:

    RESERVE_LIST.EFFECT_DATE<SYSDATE
    RESERVE_LIST.EXPIRE_DATE>SYSDATE

...and it seems to have done the trick:  https://i-share-devel.carli.illinois.edu/vf-sei/Search/Reserves

Let me know when/if I should move this over to TEST

**Comment by dmcmpbll** [comment]
Yes, I've completed some tests, I think this is ready to move to TEST.

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
Ready for Prod!
