### ISSUE TITLE
Add Journal Title to search options

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#268]
SIC - Add journal title as an option to the pull down menu.  University of Chicago has implemented a solution: https://catalog.lib.uchicago.edu/vufind/Search/Results?lookfor=hitchcock&type=AllFields

**Comment by dgree1** [comment]
Can I help with the research? Still on SFX committee's radar.

**Comment by gibsonjc** [comment]
I believe this search type is already defined in searchspecs.yaml and searches.ini.  Let's uncomment the two JournalTitle lines in searches.ini **as seen in bold below** and see if the option appears in the search type dropdown list and how it works.  Thanks!

; This section shows which search types will display in the basic search box at
; the top of most pages.  The name of each setting below corresponds with a
; search handler (either DisMax or from conf/searchspecs.yaml).  The value of
; each setting is the text to display on screen.  All on-screen text will be run
; through the translator, so be sure to update language files if necessary.  The
; order of these settings will be maintained in the drop-down list in the UI.
;
; Note: The search type of "tag" is a special case that gets handled differently
;       because tags are not stored in the same index as everything else.  Treat
;       this as a reserved word if you create your own custom search handlers.
[Basic_Searches]
AllFields           = "All Fields"
Title               = Title
**;JournalTitle        = "Journal Title"**
Author              = Author
Subject             = Subject
CallNumber          = "Call Number"
ISN                 = "ISBN/ISSN"
;Coordinate        = Coordinates
tag                 = Tag

; This section defines which search options will be included on the advanced
; search screen.  All the notes above [Basic_Searches] also apply here.
[Advanced_Searches]
AllFields           = adv_search_all
Title               = adv_search_title
**;JournalTitle        = adv_search_journaltitle**
Author              = adv_search_author
Subject             = adv_search_subject
CallNumber          = adv_search_callnumber
ISN                 = adv_search_isn
publisher           = adv_search_publisher
Series              = adv_search_series
year                = adv_search_year
toc                 = adv_search_toc
;Coordinate        = Coordinates

**Comment by dgree1** [comment]
Good idea.
I’m glad to test.
Denise

**Comment by cedelis** [comment]
Ready for Testing

Caveat: I had to also modify searchspecs.yaml because we catalog formats differently than the default VuFind index specs:

 Original:

  **FilterQuery: "format:Journal OR format:Article"**

<pre>
# This field definition is a compromise that supports both journal-level and
# article-level data.  The disadvantage is that hits in article titles will
# be mixed in.  If you are building a purely article-oriented index, you should
# customize this to remove all of the title_* fields and focus entirely on the
# container_title field.
JournalTitle:
  DismaxFields:
    - title_short^500
    - title_full_unstemmed^450
    - title_full^400
    - title^300
    - container_title^250
    - title_alt^200
    - title_new^100
    - title_old
    - series^100
    - series2
  DismaxHandler: edismax
  FilterQuery: "format:Journal OR format:Article"
</pre>

 Customized for CARLI format rules:

  **FilterQuery: "format:\"Journal / Magazine\""**

<pre>
# This field definition is a compromise that supports both journal-level and
# article-level data.  The disadvantage is that hits in article titles will
# be mixed in.  If you are building a purely article-oriented index, you should
# customize this to remove all of the title_* fields and focus entirely on the
# container_title field.
JournalTitle:
  DismaxFields:
    - title_short^500
    - title_full_unstemmed^450
    - title_full^400
    - title^300
    - container_title^250
    - title_alt^200
    - title_new^100
    - title_old
    - series^100
    - series2
  DismaxHandler: edismax
  FilterQuery: "format:\"Journal / Magazine\""
</pre>

**Comment by gibsonjc** [comment]
Thanks, this looks fantastic, and the format change to searchspecs.yaml you describe makes perfect sense.   
But I only see it in the search dropdown on TEST in local catalogs. 
https://i-share-test.carli.illinois.edu/vf-eiu/
Can it also be added for I-Share uc catalogs?
https://i-share-test.carli.illinois.edu/all/vf-eiu/
https://i-share-test.carli.illinois.edu/all/vf/

**Comment by dgree1** [comment]
I did some quick testing too and looked and worked well.
May I share with SFX Committee?
Thanks.

**Comment by cedelis** [comment]
@gibsonjc I've added the Journal Title search to the I-Share catalogs, too.

**Comment by dgree1** [comment]
Looks and functions as expected. I also tested the SFX button appearing in UC/all I-Share if the patron had either logged in and/or come to UC from a local catalog.

Ex. Via SIUC catalog with correct SFX SIUC buttons;

https://i-share-test.carli.illinois.edu/all/vf-sic/Search/Results?lookfor=%22wall+street+journal%22&type=JournalTitle&limit=20&sort=relevance

**Comment by gibsonjc** [comment]
The new Journal Title search type is ready for Prod!
