### ISSUE TITLE
how to make banners with image maps that work in responsive design

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#271]
BEN - RT 95702  now that the new VuFind interface is responsive, is there a way we can make our banners responsive? 

BEN - 12/14 conf call  
(Nancy at LFC had some thoughts)

**Comment by slknight** [comment]
EIU commenting so I can follow. 

The EIU banner is mapped and the map resizes with the image. It's not usable at small sizes though.

**Comment by gibsonjc** [comment]
EIU - We have an image map on our banner in VuFind 4.1. The map is not resizing with the image. At 100% the map is fine, but when it scales to 732px the map breaks. Is it possible to put HTML links and images in instead of a mapped image?  RT 100315

**Comment by gibsonjc** [comment]
@eschell Please see RT 100315 for include code to try. Thanks!

**Comment by eschell** [comment]
I've added "A native JavaScript solution for creating responsive image-maps that rerender on image or viewport changes."
usr/local/vufind/themes/carli/js/image-map.js

https://github.com/clarketm/image-map

This script is included in the head of the CARLI base theme via theme.config.php:
```
<?php
return array(
    'extends' => 'bootprint3',
    'js' => array(
        'googlefonts.js',
        'carli.js',
        'image-map.js',
    ),
```
the script is then called **_after_** the image-map is implemented in the header template
usr/local/vufind/themes/carli/templates/header.phtml

```
<script>
	$('img[usemap]').imageMap();
</script>
```
Since all of the institution themes are based on the CARLI theme this will work for any and all.

**Comment by gibsonjc** [comment]
In Prod. Closing.
