### ISSUE TITLE
Author info retrieved from Wikipedia is not always the correct author

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#276]
ISU - See author bio link tied to Mark Schmitt here https://i-share.carli.illinois.edu/vf-isu/Record/ISUdb.1672714

Description for cataloging staff:
When there is no Wikipedia page for an individual, then clicking on that author's name in a bib record, returns a retrieval set of catalog records for all the titles we own by that author. No problem there. Examples: Maureen Brunsdale, John Freed, Sandra K. Roe, April Karlene Anderson.

When there is a Wikipedia page for an author, the blurb "Provided by Wikipedia" is pulled into VuFind and displays above the retrieval set of works by that person. See https://i-share.carli.illinois.edu/vf-isu/Author/Home?author=Lincoln%2C+Abraham%2C+1809-1865. While the Wikipedia page title (Abraham Lincoln) and the authorized access point (Lincoln, Abraham, 1809-1865<https://i-share.carli.illinois.edu/vf-isu/Author/Home?author=Lincoln%2C+Abraham%2C+1809-1865.>) do not match, Authority Control information has been entered into Abraham Lincoln's Wikipedia page that links his LC NAR to his Wikipedia page:

Authority control<https://en.wikipedia.org/wiki/Help:Authority_control>

* WorldCat Identities<https://www.worldcat.org/identities/containsVIAFID/76349832>
* VIAF<https://en.wikipedia.org/wiki/Virtual_International_Authority_File>: 76349832<https://viaf.org/viaf/76349832>
* LCCN<https://en.wikipedia.org/wiki/Library_of_Congress_Control_Number>: n79006779<http://id.loc.gov/authorities/names/n79006779>
* ISNI<https://en.wikipedia.org/wiki/International_Standard_Name_Identifier>: 0000 0001 2102 4704<http://isni.org/isni/0000000121024704>

In Mark's case, there is a Wikipedia page for another Mark Schmitt -- the American political scientist. While there is an LC name authority record for Milner's Mark (Schmitt, Mark, 1973-), there is no Wikipedia page for him. There is no LC NAR for the American political scientist; he has a Wikipedia page but there is not any Authority Control information in it that could have differentiated him from Milner's Mark.

In the case of Charles E. Hovey, there is a Wikipedia page for him (Charles Edward Hovey<https://en.wikipedia.org/wiki/Charles_Edward_Hovey>) and there is also a LC NAR for him (Hovey, Charles E. (Charles Edward), 1827-1897). Again, there is no Authority Control information in his Wikipedia page that would link it to the LC NAR. VuFind doesn't find it, and so just a list of his authored works is retrieved.
https://i-share.carli.illinois.edu/vf-isu/Record/ISUdb.247708
https://i-share.carli.illinois.edu/vf-isu/Author/Home?author=Hovey%2C+Charles+E.+1827-1897

Looks like VuFind is searching Wikipedia precisely when it can (when there is Authority Control info in Wikipedia to latch onto and match up the authorized form in the bib record through its LC NAR) but may be taking a guess when it can't.

[Despite all of this, when asked, ISU staff replied that they would recommend keeping the feature ON in production so that they can "work on improving records and finding solutions for mismatches."  They also recommend that we try implementing the VIAF web service.  RT 96379]

**Comment by gibsonjc** [comment]
This feature in on by default and appeared after fixing author-related search redirects in #256 

There may be a way to make it "smarter" if we follow the recommendation notes in searches.ini.  We have authority records loaded, after all.

In config.ini:
[Content]
; You can select from Wikipedia
; See also the AuthorInfo recommendation module setting in searches.ini; this
; includes notes on improving the accuracy of Wikipedia retrievals.
; Note for Windows users: If using Wikipedia, you may need to increase your Apache
; heap size settings.  For details, see: https://vufind.org/jira/browse/VUFIND-630
authors = Wikipedia

searches.ini:
; AuthorInfo:[use_viaf]
;       Load author information from external providers based on the current search
;       and the "authors" setting in the [Content] section of config.ini.
;       The [use_viaf] setting may be set to true to use the VIAF web service in
;       combination with your Solr authority index to pick more appropriate authors;
;       this defaults to false if unset.  If you do not have local authority records
;       to draw on, the OCLC FAST data works well with the [use_viaf] option; see:
;       https://vufind.org/wiki/indexing:open_data_sources#oclc_fast

**Comment by dgree1** [comment]
Amanda Pippitt at MIL reported similar case with "John Adams" composer versus Pres. John Adams. 
from #100131: new VF question


Searched for: Nixon in China
Clicked on: Adams, John, 1947-
Got this: https://i-share.carli.illinois.edu/vf-mil/Author/Home?author=Adams%2C+John%2C+1947- (item results are appropriate, but Wikipedia entry given is for President, not composer John Adams).

**Comment by gibsonjc** [comment]
KNX - I'd rather see it either work properly or turned off.

RT 100515

**Comment by gibsonjc** [comment]
SIC - I just wanted to report that when you do an author search for Toews, David in the catalog it displays information at the top of the screen from Wikipedia that is inaccurate.
https://i-share.carli.illinois.edu/all/vf-sic/Author/Home?author=Toews%2C+David%2C
The picture and information provided are for hockey player David Toews.

**Comment by gibsonjc** [comment]
SVC - I found that a wikipedia link to an author bio is not correct.
https://i-share.carli.illinois.edu/all/vf-svc/Author/Home?author=Smith%2C+Amber%2C+1982-
The link is to a model with the same name but she is not the author of the books. 

RT 104685

**Comment by gibsonjc** [comment]
I don't foresee us making any large scale changes to how this feature "works" at this point, so it would be better to turn it off entirely so that it does not provide bad data.  Please comment out 

;authors = Wikipedia

in config.ini:

[Content]
; You can select from Wikipedia
; See also the AuthorInfo recommendation module setting in searches.ini; this
; includes notes on improving the accuracy of Wikipedia retrievals.
; Note for Windows users: If using Wikipedia, you may need to increase your Apache
; heap size settings. For details, see: https://vufind.org/jira/browse/VUFIND-630
authors = Wikipedia

**Comment by gibsonjc** [comment]
Discussed at April 4 meeting; @cedelis will look into linking it with authorities first.

**Comment by cedelis** [comment]
In TEST. It seems that the VuFind integration with VIAF and Wikipedia have changed recently. I had to make minor adjustments to VuFind code. I think this feature behaves better now. (It's obviously still not perfect). Let me know if you think this patch is worth moving into PROD. Otherwise, we can simply turn the feature off.  Chris

E.g.,

Current (PROD) contains false positive Wikipedia bios:
https://i-share.carli.illinois.edu/vf-isu/Author/Home?author=Schmitt%2C+Mark%2C+1973-
https://i-share.carli.illinois.edu/all/vf-svc/Author/Home?author=Smith%2C+Amber%2C+1982-
https://i-share.carli.illinois.edu/all/vf-sic/Author/Home?author=Toews%2C+David%2C

Now, TEST does not:
https://i-share-test.carli.illinois.edu/vf-isu/Author/Home?author=Schmitt%2C+Mark%2C+1973-
https://i-share-test.carli.illinois.edu/all/vf-svc/Author/Home?author=Smith%2C+Amber%2C+1982-
https://i-share-test.carli.illinois.edu/all/vf-sic/Author/Home?author=Toews%2C+David%2C

Wrong "John Adams" in PROD:
https://i-share.carli.illinois.edu/vf-mil/Author/Home?author=Adams%2C+John%2C+1947-
Correct "John Adams (composer)" in TEST:
https://i-share-test.carli.illinois.edu/vf-mil/Author/Home?author=Adams%2C+John%2C+1947-

~~However, both TEST and PROD failed to pull up "Charles E. Hovey":~~
PROD fails to pull up "Charles E. Hovey":
https://i-share.carli.illinois.edu/vf-isu/Author/Home?author=Hovey%2C+Charles+E.+1827-1897.
TEST does:
https://i-share-test.carli.illinois.edu/vf-isu/Author/Home?author=Hovey%2C+Charles+E.+1827-1897.

Edit: I've added a second attempt authority search for when the default (MainHeading) search fails. This (AllFields) search is more lenient, and as a result the "Charles E. Hovey" search succeeds.

E.g.,
MainHeading authority search: 
{&q="Hovey,+Charles+E.+1827-1897"
&qt=edismax
&qf=heading_keywords^750
&bq=(record_type:"Personal+Name"+OR+record_type:"Corporate+Name")^500} hits=0 status=0 QTime=0

AllFields authority search:
{&q="Hovey,+Charles+E.+1827-1897"
&qt=edismax
&qf=heading_keywords^750+use_for_keywords^400+see_also_keywords^100+allfields
&bq=(record_type:"Personal+Name"+OR+record_type:"Corporate+Name")^500} hits=1 status=0 QTime=0

**Comment by gibsonjc** [comment]
I haven't found any searches in TEST that are worse off because of these changes.  Ready for Prod!

**Comment by cedelis** [comment]
In PROD
