### ISSUE TITLE
Created date on Requested Items tab

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#277]
Each requested item listed on the Requested Items tab contains a date row labeled "Created". The label remains consistent (as "Created") even as the date itself is updated to represent other dates in Voyager. 

Phases:
1) When a request is first placed (or first promoted into a database), the label "Created" is accurate enough. 
2) When the call slip request is then printed by library staff, the date updates to be the "Printed" date.
3) When the call slip request is filled by library staff, the date updates to be the in transit on hold interval.
4) When the item is discharged at the pick-up library for the hold shelf, the date updates to be the hold shelf interval. aka Available for Pickup.

![image](https://user-images.githubusercontent.com/20848151/34173609-a1e54f2c-e4bb-11e7-82f6-60acfeb3dd36.png)

States of 4 examples in screenshot from VuFind4-test, for the 4 phases mentioned above:
- Not the other: requested 
- Tom Sawyer: printed (would be different date if printed on date after requested, but i set up this example entirely today, so both dates are the same)
- Birth of feminism: filled, "In Transit- On Hold" status
- To the ends: routed in; On Hold at pickup library

In VuFind 0.6, a date does not show until the item is "On Hold" aka Available for Pickup.

![image](https://user-images.githubusercontent.com/20848151/34173770-32e4d998-e4bc-11e7-9b66-459fd440c3c4.png)

The terms used to describe the states in VuFind 0.6 are:
- Not the other: "Request submitted"
- Tom Sawyer: "Request in process"
- Birth of feminism: "Requested item in transit"
- To the ends: "Available for pickup until [DATE]"

I would recommend hiding the “Created date” labeled field on the “Requested Items” tab, if hiding it is easier than making it accurate. 
As mentioned above, VuFind 0.6 does not show a date until the item is "On Hold" aka Available for Pickup.

**Comment by gibsonjc** [comment]
Let's see if we can duplicate the functionality of VuFind 0.6 where a request displays one of four different statuses rather than a single misleading label "Created" and a changing date.  The date really is only useful to display when the item is available to be picked up to let people know how long they have to go get it.

1. When a request is first placed (or first promoted into a database), show "Request submitted"

2. When the call slip request is then printed by library staff, show "Request in process"

3. When the call slip request is filled by library staff, show "Requested item in transit"

4. When the item is discharged at the pick-up library for the hold shelf, show "Available for pickup until [DATE]"

@dmcmpbll are the examples already shown in this Issue still available for using for testing on TEST?  Are these in your UIUC account or an account that we can view (non-Shibboleth library).  If so, can you provide information on it via email.  If not, we'll need to set up some examples on TEST for testing.  Thanks!

**Comment by dmcmpbll** [comment]
Will email a new example set to @cedelis and @gibsonjc 
Thanks!

**Comment by dmcmpbll** [comment]
Hi! I'll resend the examples from Feb 9th; they are still be entered in Test.
Please let me know if you'd like a set of examples on Devel instead.

Screenshots from the text examples in VuFind 0.6 and New VuFind are below.

![vufind0 6examples](https://user-images.githubusercontent.com/20848151/38893307-8fa2de8c-424f-11e8-87c9-bbf4249e8fcb.PNG)

![newvufindexamples](https://user-images.githubusercontent.com/20848151/38893315-9323b8ba-424f-11e8-8d43-33653b1ccb24.PNG)

**Comment by dmcmpbll** [comment]
UIU- "I'm forwarding you this request we had from patron asking about the inclusion of status of Requested items. It was a feature of VuFind 0.6 but the status information is not included in the initial list of requested items. Someone showed up at the desk of one of our libraries today at UIUC but the requests had not been processed."

RT 99607

**Comment by gibsonjc** [comment]
UIU - Patron reported being confused by "Created:" dates for requested items. Note the dates are in the future.

Also note that the dates correspond to the Voyager-side "Expires" dates for their in-transit requests.

The dates in the "future" seem potentially confusing for patrons.

RT 99717

**Comment by cedelis** [comment]
In TEST.

**Comment by cedelis** [comment]
In PROD
