### ISSUE TITLE
Fines in Your Account do not display which library the Fine is from

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#28]
The Fines and fee section of Your Account is not consortially aware.

**Comment by cedelis** [comment]
I had to rewrite a *lot* of themes/bootprint3/templates/myresearch/fines.phtml 
It's a small template file, but it's mostly customized now.
I also had to make some changes to the XNCIP2 driver ( module/VuFind/src/VuFind/ILS/Driver/XCNCIP2.php ) so that it now exposes the library information of each item. The XC NCIP server was slightly tweaked to provide this same information).
