### ISSUE TITLE
Location name displaying in Pick Up Location dropdown

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#286]
UIC - open call 12/15/2017

In WebVoyage and VuFind 0.6, the Pick Up Location name that displays during a request transaction is the Location's "Name" in Voyager Sys Admin.  (See also page 6 of https://www.carli.illinois.edu/sites/files/i-share/documentation/secure/system.pdf) 

In New VuFind, the Pick Up Location name that displays during a request transaction is the Location's "OPAC Display Name" in Voyager Sys Admin.

Example Location for UIC:
code = MainCirc
Name = Daley - Circulation Desk
OPAC Display Name = UIC.MainCirc

![screen shot 2018-01-12 at 2 54 21 pm](https://user-images.githubusercontent.com/17598357/34894957-220a26be-f7a9-11e7-853d-f91673f18487.png)
![screen shot 2018-01-12 at 2 54 06 pm](https://user-images.githubusercontent.com/17598357/34894970-2c8d5f16-f7a9-11e7-8270-e9aae38f62be.png)

**Comment by gibsonjc** [comment]
@dmcmpbll   This behavior differs from 0.6 and WebV, but I'm also not sure about this choice of OPAC Display Name.  I'd appreciate your opinion on if we should try to change what New VuFind does (not sure how easy or hard that would be) or recommend that libraries implement OPAC Display Names that are meaningful (when they do choose to use them) because New VuFind is going to use them here.

**Comment by dmcmpbll** [comment]
Background from the CARLI SysAdmin documentation:
- Location Name: This name will display alphabetically in drop-down lists in the Voyager staff clients. Unless you enter an OPAC Display Name, Voyager will also display this name as your OPAC holdings location descriptions. [...] For the Circulation HAPPENING locations... this Location Name will be shown in the OPAC in the list of available pick-up locations.
- OPAC Display Name: If you enter an OPAC display name, this name will display in the OPAC. THis enables libraries to enter a name that would be more meaningful/helpful to patrons trying to locate the item.

Thoughts: 
- Having the OPAC display name for a Circ Happening Location display in the OPAC would make the term "OPAC display name" actually always mean that it's the name that patrons will always see in the OPAC, regardless of whether it is a shelving location name, or a happening location name.
- What is lost is the ability for the Location Name to display in the drop-down menus like ".MAIN CIRC", and be listed for materials shelved at those locations by the OPAC Display Name like  "Ask at Library Circulation Desk." 
-The Location Name (not Display Name) would continue to be what was printed on patron notices. https://www.carli.illinois.edu/products-services/i-share/circ/secure/LibraryAddressInVoyager 

I think I'd recommend that libraries implement OPAC Display Names that are meaningful, since the Location Name still prints on any patron notices. The OPAC Display Name can be 60 characters long, so libraries may be able to craft a naming convention that covers both pick-up and shelved collections in both cases.

**Comment by dmcmpbll** [comment]
Additional thought about the OPAC display name: It is nice to use because for Circ Happening Location Name, our consortial convention is to have libraries enter the name in all caps, so like ".CIRCULATION DESK". Using the OPAC display name would allow libraries to be more deliberate about what the patrons see while being able to keep with the consortial convention for the name, so "Name of Library Circulation Desk" <-- In regular capitalization.

**Comment by gibsonjc** [comment]
This is a change in functionality, not a bug, and libraries may wish to revisit the OPAC Display names for their Circ happening locations in Voyager SysAdmin. We will document it on the differences page .

**Comment by gibsonjc** [comment]
Documented here: https://www.carli.illinois.edu/products-services/i-share/opac/opac_differences
@dmcmpbll - please feel free to adjust the wording there!
Closing this Issue.
