### ISSUE TITLE
Ability to select multiple search results for same action

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#300]
In WebVoyage Classic, it was possible to select multiple search results for the same, simultaneous action (Print/Download/Email).  Would it be possible for New VuFind to have similar "select multiple" functionality?

RT98185- RSH

**WebVoyage screenshots:**
1) Selection checkboxes:
![image](https://user-images.githubusercontent.com/20848151/37492022-b2372058-286d-11e8-8b8e-9f952bbadeed.png)

2) Options for selected check-boxes at bottom of page:
![image](https://user-images.githubusercontent.com/20848151/37492052-d6791444-286d-11e8-8b63-5eb68ef00b87.png)

**Comment by gibsonjc** [comment]
In config.ini, I think this might be:
https://github.com/vufind-org/vufind/blob/c02b20dd4a628bd83a062b91cd49c56f0ecb2eca/config/vufind/config.ini#L133

```
; Display bulk items (export, save, etc.) and checkboxes on search result screens?
showBulkOptions = false
```

Change to **true** and checkboxes will appear for each item in the search results list along with export/save options somewhere on the page?

**Comment by gibsonjc** [comment]
@cedelis When you get a chance, could you make this change on DEVEL so we can see what it looks like and how it works?  I'm not sure if we'll want it or not so don't want it on TEST yet.

In config.ini, change 
```
; Display bulk items (export, save, etc.) and checkboxes on search result screens?
showBulkOptions = false
```
to 

**showBulkOptions = true**

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
This change works as I expected it to, providing checkboxes for each item in the results list and the Email|Export|Print|Save options (it doesn't look like we have any control over these; it's all of them or nothing).  But in the I-Share uc, the links generated to the records with these functions use the uc MST MAS IDs, which we know are not permanent.  In the local catalogs, this works fine because the Voyager BIB IDs in the links are persistent.  

So we could either not turn this on at all, or we could enable this functionality for local catalogs but not for the uc.  Anyone have any opinions on what would be most helpful and least confusing?

**Comment by cedelis** [comment]
In PROD.
