### ISSUE TITLE
Strip punctuation from ends of *_facet fields

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#319]
Creating an Issue for an improvement discussed in today's meeting.  It is already in place on DEVEL.

Compare the Author facet on
https://i-share-test.carli.illinois.edu/vf-uiu/Search/Results?lookfor=pratchett%2C+terry&type=Author
to
https://i-share-devel.carli.illinois.edu/vf-uiu/Search/Results?lookfor=pratchett%2C+terry&type=Author 
and note the consolidated headings

**Comment by gibsonjc** [comment]
This change to the facet fields to strip commas at the end looks good on DEVEL.  Please put in place on TEST when you get a chance.  Thanks!

**Comment by cedelis** [comment]
Related to Issue #287 

This is currently merged in an issue-specific branch. It would be easier to pull this specific change ( commit b81d359e4633d587ad542ecc55ece45c52a0d777 ) along with Issue #287 , since the modification to file schema.xml contains other changes (which are not ready to do right now). In the meantime, I can (and will, at the time of this writing) manually edit this on TEST temporarily (not formally) so that we can see the effect on TEST. [Edit: never mind, since this will require a complete reindex; it doesn't make sense to do now; need to wait till Issue #287]

**Comment by cedelis** [comment]
In prod.

**Comment by gibsonjc** [comment]
Done in local catalogs but I'm reopening this Issue because it still needs to be done for the uc catalog.  Aim to start work Tue. June 5.

**Comment by cedelis** [comment]
Last week, we reindexed the uc catalog.
