### ISSUE TITLE
Default pick-up location for library is not being honored

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#333]
UIU - RT 99594

**Comment by cedelis** [comment]
In Test

**Comment by cedelis** [comment]
Added code to pre-select the system-wide default if patron hasn't yet chosen their own preferred pickup location

cd4682ac7029162d493ce370579377cf2d2787c2

**Comment by gibsonjc** [comment]
UIU - We've found that the issue reported in CARLI Support ticket #99594 (where patron's default pickup location for items was UIUC ACES DESK rather than UIUC MAIN STACKS DESK) appears to not have been corrected for our courtesy card users (patron group code LL, LH, LB).

A courtesy card patron reported this this afternoon and the error has been tested by staff using LL account 20112000204387 Whoopi Goldberg. Items requested by LL, LH, and LB patrons still default to UIUC ACES DESK and we would like them to default to UIUC MAIN STACKS DESK.

We consider this an urgent ticket as we have a large group of visiting scholars using LH cards over the next month or so.

RT 100065

@cedelis can you have a look?  Thanks!

**Comment by cedelis** [comment]
@gibsonjc  I think I know what's happening here. 

First of all: The only Voyager API service that I know of that can retrieve the system-wide default pickup location is: https://developers.exlibrisgroup.com/voyager/apis/XMLoverHTTPWebServices/UBPickupLibService

But that service seems to only work for "UB-enabled" patrons, because:

a) For patrons who are not "UB-enabled," I get an error message:

<ser:voyagerServiceData xmlns:ser="http://www.endinfosys.com/Voyager/serviceParameters">
  <ser:messages>
    <ser:message type="system" errorCode="com.endinfosys.voyager.requests.exceptions.PatronRequestsException">Could not find request: \'UB\'</ser:message>
  </ser:messages>
</ser:voyagerServiceData>

b) But for patrons who are "UB-enabled," I receive the following information which includes the default pickup location (of UIUC MAIN STACKS CIRCULATION DESK):

<ser:voyagerServiceData xmlns:ser="http://www.endinfosys.com/Voyager/serviceParameters">
  <ser:serviceData xmlns:req="http://www.endinfosys.com/Voyager/requests" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="req:requestsCollectionType">
    <req:requestDefinition>
      <req:requestIdentifier requestCode="UB" requestName="Request first available copy" requestType="S"/>
      <req:pickUpLocations>
        <req:location id="376" isDefault="Y">UIUC MAIN STACKS CIRCULATION DESK</req:location>
        <req:location id="356">UIUC ACES CIRCULATION DESK</req:location>
        <req:location id="357">UIUC ART CIRCULATION DESK</req:location>
        <req:location id="353">UIUC CAMPUS MAIL</req:location>
        <req:location id="361">UIUC CHEMISTRY CIRCULATION DESK</req:location>
        <req:location id="365">UIUC COMMUNICATIONS CIRCULATION DESK</req:location>
        <req:location id="370">UIUC ENGINEERING CIRCULATION DESK</req:location>
        <req:location id="371">UIUC HISTORY, PHILOSOPHY &amp; NEWSPAPER CIRCULATION DESK</req:location>
        <req:location id="787">UIUC INTERATIONAL &amp; AREA STUDIES CIRCULATION  DESK</req:location>
        <req:location id="406">UIUC ILL Lending</req:location>
        <req:location id="374">UIUC LAW CIRCULATION DESK</req:location>
        <req:location id="758">UIUC LITERATURES &amp; LANGUAGES CIRCULATION DESK</req:location>
        <req:location id="377">UIUC MAP &amp; GEOGRAPHY CIRCULATION DESK</req:location>
        <req:location id="378">UIUC MATH CIRCULATION DESK</req:location>
        <req:location id="380">UIUC MUSIC CIRCULATION DESK</req:location>
        <req:location id="482">UIUC OAK STREET FACILITY CIRCULATION DESK</req:location>
        <req:location id="694">UIUC RESIDENCE HALL LIBRARIES ILLINOIS STREET</req:location>
        <req:location id="743">UIUC RESIDENCE HALL LIBRARIES IKENBERRY COMMON</req:location>
        <req:location id="688">UIUC RESIDENCE HALL LIBRARIES</req:location>
        <req:location id="698">UIUC RESIDENCE HALL LIBRARIES RESOURCE CENTER</req:location>
        <req:location id="795">UIUC SOC SCI, HLTH, &amp; ED LIBRARY</req:location>
        <req:location id="384">UIUC UNDERGRAD CIRCULATION DESK</req:location>
        <req:location id="385">UIUC UNI HIGH CIRCULATION DESK</req:location>
      </req:pickUpLocations>
    </req:requestDefinition>
  </ser:serviceData>
</ser:voyagerServiceData>


However, there *is* a way to manually configure a default pickup location on a library-per-library basis, via their config.ini:

; A Pick Up Location Code used to pre-select the pick up location drop down list and
; provide a default option if others are not available. Must be one of the following:
; 1) empty string to indicate that the first location is default (default setting)
; 2) "user-selected" to indicate that the user always has to choose the location
; 3) a value within the Location IDs returned by getPickUpLocations()
defaultPickUpLocation = "376"


Currently, the defaultPickUpLocation parameter is not set (by default). I could set this value to 376, which would provide a single default pickup location for non-UB-enabled patrons.

It seems like we need to bypass the Voyager API and rely on the hard-coded config parameter. @fellowsgl  Can you please send me a list of default location codes for each CARLI member library? If this is a setting that can change then we might need to consider automating this setting, too.

In the meantime, I have manually configured UIU to have a pickup location of 376, which is UIUC MAIN STACKS CIRCULATION DESK.

Chris

**Comment by cedelis** [comment]
The best solutions is to simply honor the defaultPickUpLocation value in VoyagerRestful.ini.

In PROD.
