### ISSUE TITLE
SFX button displaying when should not since title NOT active in SFX local instance

### ISSUE THREAD

**Issue by dgree1** [CARLI/vufind#335]
SFX button displaying in New VuFind when no corresponding active title in SFX knowledge base for the library. 
Examples. 
1. "Contents of contemporary mathematical journals" ISSN 0010-759X
 https://i-share.carli.illinois.edu/vf-uiu/Record/UIUdb.43001
 https://vufind.carli.illinois.edu/vf-uiu/Record/uiu_43001
 UIU bib 43001: has 022 ‡a 0010-759X
and no 022 subfield l. 

2. Journal of mathematics and applications.
(ISSN 1733-6775)
https://i-share.carli.illinois.edu/vf-uiu/Record/UIUdb.5187831 
https://vufind.carli.illinois.edu/vf-uiu/Record/uiu_5187831 
UIU bib 5187831 has 022 a 1733-6775

3. 
"Perspective [ISSN 0031-5907]"
https://i-share.carli.illinois.edu/vf-sic/Record/SICdb.597755
https://vufind.carli.illinois.edu/vf-sic/Record/sic_597755

SIC BIB 597755 has 022 a 0031-5907

New VuFind should display the SFX button/icon when three things are all true:
A. There's an ISSN in MARC field 022a or 022l.

B. The user is either in a local catalog of a CARLI SFX library via https://i-share.carli.illinois.edu/vf-xxx OR has logged into their VuFind account OR has gone into the all I-Share via a local catalog so the "vf-xxx" is there in URL.  

C. There is at least one currently active title/object portfolio in your library's SFX instance for the title that matches the ISSN from 022 field.

**Comment by gibsonjc** [comment]
@cedelis I added this one to priority issues.  I believe that SFX buttons were displaying properly before, but now they are displaying more often than they should be.  The SFX button displays in the Search Results List and in the Holdings Tab on a single record page and is behaving the same way (that is, showing up when it shouldn't) in both places.  

I can't say exactly when the behavior changed, but we did recently alter the "Internet" area of the Holdings tab in #317.  I could be wrong, but the last time we changed the behavior of the Search Results List where the SFX button shows up was back in December in #279 .  You recently made non-SFX button adjustments to the same general area of the Results List in #207 .

Also, can you confirm/deny if our understanding of the logic that drives the SFX button to display is correct? (Please see Denise's previous comment with ABC). This is a little bit of a black box to me since New VuFind comes preconfigured to work with a link resolver, and specifically with SFX.  Thanks!

**Comment by cedelis** [comment]
We currently have no custom rules for OpenURL resolvers (SFX, in our case), therefore we are using the default settings, which I believe are set in: https://github.com/CARLI/vufind/blob/carli-release-4.1/config/vufind/OpenUrlRules.json

So, it looks like our default rule is to display the SFX link (button) whenever an ISSN is available in the record. You can see the precise getCleanISSN method here: https://github.com/CARLI/vufind/blob/carli-release-4.1/module/VuFind/src/VuFind/RecordDriver/SolrDefault.php#L397

There is documentation for creating rule sets here: https://vufind.org/wiki/configuration:openurls#defining_openurl_rules

Let's take a look at Denise's list of rules above:

 
**A. There's an ISSN in MARC field 022a or 022l.**

issn is mapped correctly ( https://github.com/CARLI/vufind/blob/carli-release-4.1/import/marc_dedup_local.properties#L33 ):
 
issn = 022a:022l

**B. The user is either in a local catalog of a CARLI SFX library via https://i-share.carli.illinois.edu/vf-xxx OR has logged into their VuFind account OR has gone into the all I-Share via a local catalog so the "vf-xxx" is there in URL.**


Check.


**C. There is at least one currently active title/object portfolio in your library's SFX instance for the title that matches the ISSN from 022 field.**

I'm not certain if anything is wrong here. What I can share with you is the sfx link that VuFind creates based on the ISSN. When I go to the first example above (in DEVEL, not PROD, https://i-share-devel.carli.illinois.edu/vf-uiu/Record/UIUdb.43001 ), the resulting SFX link that gets generated is:

http://sfx.carli.illinois.edu/sfxuiu?url_ver=Z39.88-2004&ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2FEndeavor%3Agenerator&rft.title=Contents+of+contemporary+mathematical+journals.&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&rft.creator=&rft.pub=American+Mathematical+Society%2C&rft.format=Journal&rft.language=English&rft.issn=0010-759X&sfx.ignore_date_threshold=1

Here are some properties used to generate the above URL (in case it helps any):

resolverUrl => http://sfx.carli.illinois.edu/sfxuiu?url_ver=Z39.88-2004&ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2FEndeavor%3Agenerator&rft.title=Contents+of+contemporary+mathematical+journals.&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&rft.creator=&rft.pub=American+Mathematical+Society%2C&rft.format=Journal&rft.language=English&rft.issn=0010-759X&sfx.ignore_date_threshold=1,

openUrl => url_ver=Z39.88-2004&ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2FEndeavor%3Agenerator&rft.title=Contents+of+contemporary+mathematical+journals.&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&rft.creator=&rft.pub=American+Mathematical+Society%2C&rft.format=Journal&rft.language=English&rft.issn=0010-759X&sfx.ignore_date_threshold=1,

openUrlBase => http://sfx.carli.illinois.edu/sfxuiu,

openUrlWindow => toolbar=no,location=no,directories=no,buttons=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=550,height=600,

openUrlGraphic => https://sfx.carli.illinois.edu/sfxuiu/sfx.gif,

openUrlGraphicWidth => false,

openUrlGraphicHeight => false,

openUrlEmbed => false,

openUrlEmbedAutoLoad => false,

openUrlImageBasedMode => false,

openUrlImageBasedSrc => NULL,

**Comment by cedelis** [comment]
I think the problem is with C:

**C. There is at least one currently active title/object portfolio in your library's SFX instance for the title that matches the ISSN from 022 field.**

We are currently always displaying the SFX graphic (and link) if a bib has an ISSN.

In the past (version 0.6), we had repurposed a WebVoyage perl script to generate a dynamic SFX graphic. This script first queries the SFX resolver to determine if full text is available. If there is, it would return a graphic; if full text is not available, it would not.

If we want to follow the same approach, then we would need to re-install this script (or something similar) on the new VuFind server and then configure the following "dynamic graphic" parameter to reference this script:  https://github.com/CARLI/vufind/blob/master/config/vufind/config.ini#L964

**Comment by gibsonjc** [comment]
For the record, we discussed this at our meeting on 6/28 and Denise is gathering feedback from the SFX Committee (email sent 6/29).

**Comment by cedelis** [comment]
This is now in TEST.

I implemented a simple PHP dynamic image script (see below) that serves an "empty" (hidden) PNG image when/if SFX returns a "No Full text available" message. Otherwise, it will serve the standard library-specific SFX image.


<code>


$sfx_url = 'https://sfx.carli.illinois.edu/sfx' . $_SERVER['VUFIND_LIBRARY'] . '?' . $_SERVER['QUERY_STRING'];
$sfx_graphic_url = 'https://sfx.carli.illinois.edu/sfx' . $_SERVER['VUFIND_LIBRARY'] . '/sfx.gif';

$sfx_data = file_get_contents($sfx_url);

if (preg_match('/No Full text available/', $sfx_data)) {
    header('Content-Type: image/png');
    readfile('1x1.png');
    exit(0);
}

$image = file_get_contents($sfx_graphic_url);
header('Content-Type: image/gif');
echo $image;

</code>

**Comment by dgree1** [comment]
Isn’t working consistently to limit to only active portfolios in SIUC. Did work in examples sent by UIU.
I’m investigating further to see any SFX related reasons and differences in set up.

**Comment by cedelis** [comment]
In PROD.
