### ISSUE TITLE
Make Select Item box re-sizeable by user

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#377]
KNX - ...the select item box is not re-sizable by the use. For example, this box has a lot of items and it would be handy to resize the box allowing me to see more than one or two items at a time.
<img width="481" alt="screen shot 2018-08-30 at 3 08 24 pm" src="https://user-images.githubusercontent.com/17598357/44876383-91f20880-ac66-11e8-9e75-e45ce8121067.png">

Screenshot from Chrome 68.0.x.

This is another possible enhancement for future request functionality.

[JG: In my testing, I always see 5 items in the box (unless there are fewer than 5 to choose from, then the box shrinks).]

**Comment by cedelis** [comment]
In TEST. 

Note: adding the "resizable" functionality from jquery-ui has a layout side-effect. The 'Select Item' label, list control, and submit button are on separate rows. Previously, they were all on the same row. I don't think this is a show-stopper (I sort of like it better this way, personally). What do you think?

**Comment by dmcmpbll** [comment]
I agree that having the label, list control, and submit button on separate rows seems fine to me too.

I checked in Chrome, IE, and Firefox and it resized and functioned as I expected.

On my phone in Safari on Prod (so without the edits) the display box shows the first item in the list, so "any item", then when you tap on the list it shows all entries in the list and the user can select one or multiple as desired.
![prod](https://user-images.githubusercontent.com/20848151/46422335-bb84d080-c6f9-11e8-8faa-975f1d256c59.png)


On my phone in Safari on Test (so with the edit), the display box shows some dots, then when you tap on the list it shows all entries in the list and the user can select one or multiple as desired. Can the mobile display show the first list item again? Since once a user taps on the list it shows all the entries, I don't think this is too big of an issue if it cannot be fixed for mobile.
![test](https://user-images.githubusercontent.com/20848151/46422344-c17ab180-c6f9-11e8-9de3-6466aa25649d.png)

**Comment by cedelis** [comment]
@dmcmpbll Can you look at TEST now? For mobile devices, I set an initial height for the resizable list control (large enough for the 'any item' option to display).

**Comment by dmcmpbll** [comment]
yes, that looks great on TEST on my phone now- the "any item" option displays.

As expected, there was no change on my computer for IE, Firefox, or Chrome.

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD
