### ISSUE TITLE
Allow user to adjust the number of results on the page from 20

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#391]
KNX - It would be nice to have a toggle to change the number of results displayed on a page. I suppose the number "20" is fixed for all results pages, including reserves.

**Comment by gibsonjc** [comment]
This needs research.  Is there a setting somewhere already defined that we can turn on?  If not, could this be a bad idea for performance reasons and that's why they limited it to 20?

**Comment by cedelis** [comment]
In TEST

Yes, this is configurable:

https://github.com/CARLI/vufind/blob/carli-release-4.1/config/vufind/searches.ini#L27

; This section controls the result limit options for search results. default_limit
; sets the default number of results per page. limit_options is a comma-separated
; list of numbers to be presented to the end-user. If only one limit is required,
; set default_limit and leave limit_options commented out.
; WARNING: using large limits may require you to raise your PHP memory limits to
; avoid errors.
default_limit        = 20
;limit_options        = 10,20,40,60,80,100

In TEST, I've un-commented-out limit_option, so now there is a choice among 10,20,40,60,80, and 100 (default 20).

These same configuration options are available for Reserves searches, too, but it's not documented. However, after using the same settings for Reserves, I noticed that only the 'default_limit' value was honored. In order to offer the user the ability to select available limit options, I had to edit the template to render the control. I've done this, too, in TEST:


<code>
diff --git a/themes/carli/templates/search/reservessearch.phtml b/themes/carli/templates/search/reservessearch.phtml
index b55aeab..efd97cc 100644
--- a/themes/carli/templates/search/reservessearch.phtml
+++ b/themes/carli/templates/search/reservessearch.phtml
@@ -43,6 +43,7 @@

     <? if ($recordTotal > 0): ?>
       <div class="pull-right flip">
+<?=$this->render('search/controls/limit.phtml')?>
         <?=$this->render('search/controls/sort.phtml')?>
       </div>
     <? endif; ?>
@@ -53,6 +54,7 @@
       <p class="error"><?=$this->transEsc('nohit_parse_error')?></p>
     <? endif; ?>
   <? else: ?>
+
     <table class="table table-striped">
     <tr>
       <th class="department"><?=$this->transEsc('Department')?></th>
</code>

**Comment by gibsonjc** [comment]
The number of results options seems to be working well in searches and in Reserves. Will wait for @dmcmpbll to weigh in on her testing before next step.  

Anyone have opinions on the number of choices? There's nothing wrong with 10 20 40 60 80 100, but maybe 10 20 50 100 would be enough?

**Comment by gibsonjc** [comment]
At our 4/25 meeting we decided to make the choices: 10, 20, 40, 60

**Comment by gibsonjc** [comment]
@cedelis can you adjust these choices on TEST to: 10, 20, 40, 60
Thanks!

**Comment by cedelis** [comment]
@gibsonjc These have been adjusted. Thanks

**Comment by gibsonjc** [comment]
This is ready for Prod!

**Comment by cedelis** [comment]
In PROD
