### ISSUE TITLE
Requestability not apparent

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#44]
NIU- I also noticed an issue that [is] a problem in the [current] version of VuFind: you do not immediately know that an item is not requestable. For instance, many I-Share libraries will not send DVD copies of older films (pre-1970 movies) to other institutions—and many will only allow patrons to view the DVD in its home library. It is not immediately apparent when you look at the record.

niu

**Comment by bgant** [comment]
UIS - There is no status displayed in the search results to let the patron know if the item is available.

**Comment by bgant** [comment]
Trinity Christian College - Along the same lines, our copy of that title is currently overdue, but there is no indication of the item status when looking at either the I-Share catalog or our library catalog. I see that the Available status does show on applicable items, but it would be useful to carry over the other information (unavailable, due ____, overdue, overdue assumed lost, etc.) so users know what’s going on with the item. (Otherwise I’m going to have confused students looking on the shelves when the system already knows the item isn’t in the building.)

**Comment by gibsonjc** [comment]
Whether or not an item can be requested by a particular user is dependent on a complicated matrix of information specific to the item's owning library, item type, patron group, and patron record information. It is not possible for VuFind 3 (or VuFind 0.6 or WebVoyage) to preprocess all of this information in order to tell a user up front if an item is requestable by him/her or not.  

When possible, CARLI does encourage libraries to use tricks like naming locations with additional text to advertise that items in a location are not requestable, or text in publicly displaying holdings notes.
