### ISSUE TITLE
Will AD/LDAP be supported for authentication?

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#46]
Rush uses AD/LDAP for authentication. Will VuFind 3 only support Shibboleth?

**Comment by bgant** [comment]
We have reviewed using AD/LDAP for authentication. This is not a secure solution because CARLI (acting as a third-party vendor) would collect (and would see) the username and password before sending it to the campus AD/LDAP for authentication.

The better solution is to use Token based authentication where we send the user to your institution to authenticate against your AD/LDAP with their campus username and password. The institution would then send a token (no password) confirming that the user is who they claim to be.

We have enabled the Shibboleth Federation InCommon.org and we plan to work with individual campuses that can support point-to-point Shibboleth.
