### ISSUE TITLE
Migrate Username/Password from VuFind 0.6 to VuFind 3.x

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#85]
Trinity Christian College - Student Staff Member Response(s):  “I like the new set up, but it seems like the login process has changed? Is there a way for us to keep our same login information?”  Staff identified how the new login works, but we’re curious about how information from the old login will migrate to the new (see comments below).

**Comment by bgant** [comment]
Our goal with the VuFind 3.x system is to not store any usernames and passwords in VuFind itself. We plan to use Token based authentication with Shibboleth so that users authenticate with their home institution and the institution just lets our server know that the user has been authenticated.

For those that are not using Shibboleth on their campus, the default option is to login using Voyager credentials (Last Name / Barcode).

**Comment by gibsonjc** [comment]
MIL - this version moves away from creating an account with your own, self-determined username and password and back to the Library Borrower ID/Last name option.  As a librarian, I like this (makes it easy to investigate patron accounts and less frustrating when I’m trying to help them create an account and they’re confused that their username is already taken, or when they’ve forgotten the password they set), but I’m not sure the patrons will like that.

**Comment by gibsonjc** [comment]
LCC - I'm wondering as the reversion back to library borrower ID/last name for logins would diminish a large number of questions we have concerning what patrons can access with their various username and password combinations. RT87258

**Comment by gibsonjc** [comment]
ONU - The login credentials for VuFind3 are currently Barcode and Last Name.  Reading through the FAQs it seems like that’s the way it will stay.  Apparently there is capability for single sign-on depending on whether it’s compatible with the technology we have.  Otherwise, it will make accessing patron accounts easier for us and less complicated in terms of explaining the steps to patrons.  (It will also take away one of the students’ assignments for orientation!)

ONU - One of the assignments for our "College Essentials" course that all freshmen take is to create a library account. Since that goes away with VuFind 3 going back to barcode/last name access, our decision to move to VuFind 3 needs to be somewhat tied to that course.

ONU - Do not like having to use ID # and last name to sign in. This will make it harder to assist a patron off campus. It seems like it wouldn’t be as secure either.

ONU - ID# login - gets pros and cons. My vote is for whatever the patrons will find easiest and we can adapt our processes accordingly!

RT 89491
