### ISSUE TITLE
Autofill Pick-up Location to patron home institution or use "Preferred Library" set in your account

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#89]
Trinity Christian College - Is there some way to autofill the pickup location when using the Request Item box? If it could automatically insert a home campus pickup location, that would greatly speed the process (again, especially for those of us near the end of the alphabet, particularly since patrons don’t necessarily know what those three-letter codes at the beginning of each line mean). Those who would like to pick it up elsewhere could still change the location, but those who don’t know the difference wouldn’t have to wade through the (rather large) list of options.

**Comment by dmcmpbll** [comment]
During testing today in VuFind3 on prod, I requested some books for myself.
Even though I have set a pick-up location preference in my user account, VuFind3 is displaying the item's home library-default location in the request window; it is not using my preference.

Screenshot is of my request for a SAI book; the fields in the request form are filled out for SAI. 
My preference is set to UIU-Campus Mail. 

When I adjust the pick-up library to be UIU in the request form, the pick-up location is updated to be UIU's default-location "Main Stacks". 
![preferencedoesn tpreference](https://cloud.githubusercontent.com/assets/20848151/26643705/debeb270-45f7-11e7-8613-dc79cfc64e6f.PNG)

**Comment by gibsonjc** [comment]
TRN - In the current catalog, a user’s preference for pick-up library defaults to their home library so that location automatically appears when requesting an item from I-Share. In VuFind 3, there is no place to specify pick-up library preferences, so **the system appears to default to the home library for the item. Can it be changed to default to the home library for the patron?** Since a patron has to log in before reaching the pick-up screen, the system should be aware of the patron’s home library. I anticipate a lot of confusion and books being held in unexpected (and unhelpful) locations as a result of the current behavior.

**Comment by gibsonjc** [comment]
ONU - I will add (or hopefully reiterate what was already said) that the current functionality most concerning to me from a procedural standpoint involves the I-Share request. When a patron makes a request in VuFind 3, it appears that the LENDING library defaults as the pickup library. In the current VuFind it is the home library of the patron requesting the item which seems to make much more sense. Our Circulation/ILL staff envision patrons not recognizing the difference and just clicking through without paying close attention. This seemingly could lead to a lot of confusion on the part of staff and patrons. 

ONU - When requesting an item, the lender that the patron selects comes up as the pick up library. This should default to the patron’s home library.

ONU- Pick up location should default to patron's home library - Is the beta just not identifying the home library?

**Comment by gibsonjc** [comment]
TIU - 12/14/2017 open call

**Comment by gibsonjc** [comment]
NPU - When I try requesting items, the default pickup location seems to be the library that holds the item and not the patron’s institution. For example, if I request an UIC item the default pickup location seems to be UIC and not NPU. I think that many patrons would miss this and would use the wrong pickup location. Is it possible to change this so that it defaults to the patron’s home library (or allow the user to set a default pickup location?)

(...the course reserve list functionality as well as the default pick-up locations for I-Share requests are reason enough to hold off making the change [to New VuFind in January])

**Comment by gibsonjc** [comment]
UIC - 12/15/2017 open call

**Comment by cedelis** [comment]
The pickup location now defaults to the patron's home institution.

Also, since the "Preferred Library" pickup is not being honored, I have removed it from the Profile settings page (since it can only cause confusion).

**Comment by cedelis** [comment]
Looks like I figured out a solution to the "Preferred Library" issue. It has been reinstated.
Commit dd1cc528f90a2b0bc6f32fd23355482251d14a52

**Comment by dmcmpbll** [comment]
In i-share-test for UIU, I can see the drop-down menu for "Preferred Library", but I do not see the drop-down for the preferred institution. 
![image](https://user-images.githubusercontent.com/20848151/34271706-1de43d16-e653-11e7-8a06-509adea0514b.png)

In i-share-test for MIL, I do not see either drop-down menu.
![image](https://user-images.githubusercontent.com/20848151/34271740-423be57e-e653-11e7-9343-059483def18b.png)

**Comment by dmcmpbll** [comment]
For the record, VuFind 0.6 allows patrons to set both library and location in preferences. Some patrons may live closer to another I-Share library than their home library, and may wish to pick up there.

![image](https://user-images.githubusercontent.com/20848151/34271883-c404e25e-e653-11e7-8a3a-91d14c2c71aa.png)

**Comment by cedelis** [comment]
@dmcmpbll I understand that it makes sense for pick-up library to also exist on this form, but as of now, this feature does not yet exist in vufind4+. I would need to add this feature, i.e., this would technically be a feature request.

**Comment by dmcmpbll** [comment]
Gotcha- so adding "pick-up library" would be an enhancement. I will create a new Git Hub ticket for this enhancement and connect it to this ticket.

Should "pick-up location" be currently showing in all libs in i-share-test? I saw it in UIU, but not in MIL.

**Comment by cedelis** [comment]
@dmcmpbll Currently, the form is designed to only show the pick-up library control if an institution has more than one to choose from. It hides this information completely, otherwise.

**Comment by dmcmpbll** [comment]
@cedelis ah yes! Millikin has only one pick-up location. That would make sense! thanks.

I'll add info about this to the https://www.carli.illinois.edu/products-services/i-share/opac/opac_differences page once you move the change to prod.

It correctly passed my UIU "preference-set" pick-up location through with my call slip.

**Comment by cedelis** [comment]
@dmcmpbll This was put into prod.
