### ISSUE TITLE
Documentation needed for new "All Fields" Search compared to old "Keyword" Search, and other search options

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#91]
Trinity Christian College - It would be helpful to have some documentation on the difference between the new “All Fields” search and the old “Keyword” search. They evidently work differently, as a general search for ‘education’ in our current catalog and the new VuFind retrieve quite different numbers of results (5,712 in the current vs. 5,130 in the new version). They also have different interpretations of what is most relevant to that search, but I think the new VuFind provides better top results in that regard.

**Comment by gibsonjc** [comment]
MIL - it seems the various search options (“all fields,” “title,”  “author,” “subject”) operate differently than the old versions since VuFind 3 finds very different search result numbers for the exact same search. Could there be some documentation/explanation of how the various searches work somewhere?

**Comment by gibsonjc** [comment]
Documentation on the index has been posted on the FAQ at:
https://www.carli.illinois.edu/products-services/i-share/opac/new-vufind-faq#index

Closing this Issue.
