### ISSUE TITLE
Option to Include/Exclude Government Publications

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#94]
SIE - Currently we are able to set the local catalog and I-Share to include or exclude Government publications and HathiTrust records. Is there a way to do that in VuFind 3

**Comment by gibsonjc** [comment]
LFC - I find the advanced search not as useful as the old one.  You cannot exclude HathiTrust items or government documents.  I really loved the version line

**Comment by gibsonjc** [comment]
An option to include/exclude Govt publications may be possible in future now that we are indexing the 008 byte 28 in the "gpub" solr field.

**Comment by gibsonjc** [comment]
@cedelis Can you look into creating an "exclude" function for Government Publications using the "gpub" solr field?  It should work like the Exclude Electronic and Exclude Microform features already in place.  It should appear on the Advanced search page and the Narrow Search option on the right hand side (under Exclude Microform).

**Comment by gibsonjc** [comment]
I forgot to include the specification!  
If gpub is [blank] then it is NOT a government publication.  
If gpub is [any letter] then it IS a government publication.

**Comment by cedelis** [comment]
@gibsonjc This issue will need to be tabled until we reindex. We currently do not index gpub; we only store it for (potential) display purposes. This means we cannot search on it:

Our current schema.xml:

`   <field name="gpub" type="string" indexed="false" stored="true"/>
`
We need to either change the name of "gpub" to  something like "gpub_str" and re-index, making use of dynamic field naming "magic":

` <dynamicField name="*_str" type="string" indexed="true" stored="true"/>
`
or we need to change schema.xml to:

`   <field name="gpub" type="string" indexed="true" stored="true"/>
`
and re-index...

**Comment by gibsonjc** [comment]
@cedelis With this gpub field indexed now on DEVEL, can you revisit this one and see if it's enough to add this option?

**Comment by cedelis** [comment]
Since we haven't reindexed the TEST server yet, I've put this on DEVEL for now.  I was able to easily add this option. 

facets.ini

[CheckboxFacets]
-gpub:* = "Exclude Government Publications"

[Results]
gpub = "Government Publications"


EDIT: I was able to create an alias for gpub so that the facet applied label looks much better ("Government Publications" instead of "Other"):

~~There is one not-so-great (but not completely terrible either) side-effect. Once you select it, the facet list will show a weird facet applied label of "NOT Other:*"  There isn't an easy way to fix this without having to dig into the internals of Solr Query parsing (which is what I had to do with "Hide eResources to which I don't have access" feature).~~

**Comment by gibsonjc** [comment]
Looks good.  This new Gov Pubs option will move to TEST when we move the whole group of DEVEL improvements to TEST.

**Comment by gibsonjc** [comment]
Rechecked on TEST. Is working as expected and ready for Prod!

**Comment by cedelis** [comment]
In PROD
